// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BagMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BagList_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BagList_C) Reset()         { *m = BagList_C{} }
func (m *BagList_C) String() string { return proto.CompactTextString(m) }
func (*BagList_C) ProtoMessage()    {}
func (*BagList_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_BagMsg_1eb9dd89879f4b03, []int{0}
}
func (m *BagList_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BagList_C.Unmarshal(m, b)
}
func (m *BagList_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BagList_C.Marshal(b, m, deterministic)
}
func (dst *BagList_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BagList_C.Merge(dst, src)
}
func (m *BagList_C) XXX_Size() int {
	return xxx_messageInfo_BagList_C.Size(m)
}
func (m *BagList_C) XXX_DiscardUnknown() {
	xxx_messageInfo_BagList_C.DiscardUnknown(m)
}

var xxx_messageInfo_BagList_C proto.InternalMessageInfo

type BagList_S struct {
	ItemVo               []*NetItemVO `protobuf:"bytes,1,rep,name=itemVo" json:"itemVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BagList_S) Reset()         { *m = BagList_S{} }
func (m *BagList_S) String() string { return proto.CompactTextString(m) }
func (*BagList_S) ProtoMessage()    {}
func (*BagList_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_BagMsg_1eb9dd89879f4b03, []int{1}
}
func (m *BagList_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BagList_S.Unmarshal(m, b)
}
func (m *BagList_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BagList_S.Marshal(b, m, deterministic)
}
func (dst *BagList_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BagList_S.Merge(dst, src)
}
func (m *BagList_S) XXX_Size() int {
	return xxx_messageInfo_BagList_S.Size(m)
}
func (m *BagList_S) XXX_DiscardUnknown() {
	xxx_messageInfo_BagList_S.DiscardUnknown(m)
}

var xxx_messageInfo_BagList_S proto.InternalMessageInfo

func (m *BagList_S) GetItemVo() []*NetItemVO {
	if m != nil {
		return m.ItemVo
	}
	return nil
}

type ItemModify_S struct {
	ItemVo               []*NetItemVO `protobuf:"bytes,1,rep,name=itemVo" json:"itemVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ItemModify_S) Reset()         { *m = ItemModify_S{} }
func (m *ItemModify_S) String() string { return proto.CompactTextString(m) }
func (*ItemModify_S) ProtoMessage()    {}
func (*ItemModify_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_BagMsg_1eb9dd89879f4b03, []int{2}
}
func (m *ItemModify_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemModify_S.Unmarshal(m, b)
}
func (m *ItemModify_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemModify_S.Marshal(b, m, deterministic)
}
func (dst *ItemModify_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemModify_S.Merge(dst, src)
}
func (m *ItemModify_S) XXX_Size() int {
	return xxx_messageInfo_ItemModify_S.Size(m)
}
func (m *ItemModify_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemModify_S.DiscardUnknown(m)
}

var xxx_messageInfo_ItemModify_S proto.InternalMessageInfo

func (m *ItemModify_S) GetItemVo() []*NetItemVO {
	if m != nil {
		return m.ItemVo
	}
	return nil
}

type UseItem_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	UseCount             *int32   `protobuf:"varint,2,opt,name=useCount" json:"useCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseItem_C) Reset()         { *m = UseItem_C{} }
func (m *UseItem_C) String() string { return proto.CompactTextString(m) }
func (*UseItem_C) ProtoMessage()    {}
func (*UseItem_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_BagMsg_1eb9dd89879f4b03, []int{3}
}
func (m *UseItem_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseItem_C.Unmarshal(m, b)
}
func (m *UseItem_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseItem_C.Marshal(b, m, deterministic)
}
func (dst *UseItem_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseItem_C.Merge(dst, src)
}
func (m *UseItem_C) XXX_Size() int {
	return xxx_messageInfo_UseItem_C.Size(m)
}
func (m *UseItem_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UseItem_C.DiscardUnknown(m)
}

var xxx_messageInfo_UseItem_C proto.InternalMessageInfo

func (m *UseItem_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UseItem_C) GetUseCount() int32 {
	if m != nil && m.UseCount != nil {
		return *m.UseCount
	}
	return 0
}

type UseItem_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UseItem_S) Reset()         { *m = UseItem_S{} }
func (m *UseItem_S) String() string { return proto.CompactTextString(m) }
func (*UseItem_S) ProtoMessage()    {}
func (*UseItem_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_BagMsg_1eb9dd89879f4b03, []int{4}
}
func (m *UseItem_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UseItem_S.Unmarshal(m, b)
}
func (m *UseItem_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UseItem_S.Marshal(b, m, deterministic)
}
func (dst *UseItem_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UseItem_S.Merge(dst, src)
}
func (m *UseItem_S) XXX_Size() int {
	return xxx_messageInfo_UseItem_S.Size(m)
}
func (m *UseItem_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UseItem_S.DiscardUnknown(m)
}

var xxx_messageInfo_UseItem_S proto.InternalMessageInfo

func (m *UseItem_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterType((*BagList_C)(nil), "message.BagList_C")
	proto.RegisterType((*BagList_S)(nil), "message.BagList_S")
	proto.RegisterType((*ItemModify_S)(nil), "message.ItemModify_S")
	proto.RegisterType((*UseItem_C)(nil), "message.UseItem_C")
	proto.RegisterType((*UseItem_S)(nil), "message.UseItem_S")
}

func init() { proto.RegisterFile("BagMsg.proto", fileDescriptor_BagMsg_1eb9dd89879f4b03) }

var fileDescriptor_BagMsg_1eb9dd89879f4b03 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x71, 0x4a, 0x4c, 0xf7,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87, 0x08, 0x2b, 0x71, 0x73, 0x71, 0x3a,
	0x25, 0xa6, 0xfb, 0x64, 0x16, 0x97, 0xc4, 0x3b, 0x2b, 0x99, 0x23, 0x38, 0xc1, 0x42, 0x5a, 0x5c,
	0x6c, 0x99, 0x25, 0xa9, 0xb9, 0x61, 0xf9, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x42, 0x7a,
	0x50, 0x13, 0xf4, 0xfc, 0x52, 0x4b, 0x3c, 0x41, 0x32, 0xfe, 0x41, 0x50, 0x15, 0x4a, 0x56, 0x5c,
	0x3c, 0x20, 0x11, 0xdf, 0xfc, 0x94, 0xcc, 0xb4, 0x4a, 0x12, 0xf5, 0x5a, 0x73, 0x71, 0x86, 0x16,
	0xa7, 0x82, 0x04, 0xe3, 0x9d, 0x85, 0x84, 0xb8, 0x58, 0xd2, 0x4b, 0x33, 0x53, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x98, 0x83, 0xc0, 0x6c, 0x21, 0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0x54, 0xe7, 0xfc, 0xd2,
	0xbc, 0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x38, 0x5f, 0x49, 0x0f, 0xa1, 0x39, 0x58,
	0x48, 0x91, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x15, 0xac, 0x99, 0xdb, 0x88, 0x17, 0x6e, 0xa7, 0x73,
	0x7e, 0x4a, 0x6a, 0x10, 0x58, 0xca, 0x49, 0x94, 0x8b, 0x3b, 0x39, 0x3f, 0x17, 0x26, 0xe3, 0xc4,
	0x06, 0x09, 0x22, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xba, 0x1c, 0xfc, 0x2b, 0x01, 0x00,
	0x00,
}
