// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BaseVO.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ElementType int32

const (
	ElementType_ElementType_Role    ElementType = 1
	ElementType_ElementType_Monster ElementType = 2
)

var ElementType_name = map[int32]string{
	1: "ElementType_Role",
	2: "ElementType_Monster",
}
var ElementType_value = map[string]int32{
	"ElementType_Role":    1,
	"ElementType_Monster": 2,
}

func (x ElementType) Enum() *ElementType {
	p := new(ElementType)
	*p = x
	return p
}
func (x ElementType) String() string {
	return proto.EnumName(ElementType_name, int32(x))
}
func (x *ElementType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ElementType_value, data, "ElementType")
	if err != nil {
		return err
	}
	*x = ElementType(value)
	return nil
}
func (ElementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{0}
}

type Code struct {
	Code                 *int32   `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Params               []string `protobuf:"bytes,2,rep,name=params" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Code) Reset()         { *m = Code{} }
func (m *Code) String() string { return proto.CompactTextString(m) }
func (*Code) ProtoMessage()    {}
func (*Code) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{0}
}
func (m *Code) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Code.Unmarshal(m, b)
}
func (m *Code) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Code.Marshal(b, m, deterministic)
}
func (dst *Code) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Code.Merge(dst, src)
}
func (m *Code) XXX_Size() int {
	return xxx_messageInfo_Code.Size(m)
}
func (m *Code) XXX_DiscardUnknown() {
	xxx_messageInfo_Code.DiscardUnknown(m)
}

var xxx_messageInfo_Code proto.InternalMessageInfo

func (m *Code) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Code) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

type NetUserInfo struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Gold                 *int64   `protobuf:"varint,2,opt,name=gold" json:"gold,omitempty"`
	Money                *int64   `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	Name                 *string  `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Level                *int32   `protobuf:"varint,5,opt,name=level" json:"level,omitempty"`
	Head                 *string  `protobuf:"bytes,6,opt,name=head" json:"head,omitempty"`
	IsGm                 *bool    `protobuf:"varint,7,opt,name=isGm" json:"isGm,omitempty"`
	Jiahui               *int32   `protobuf:"varint,8,opt,name=jiahui" json:"jiahui,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetUserInfo) Reset()         { *m = NetUserInfo{} }
func (m *NetUserInfo) String() string { return proto.CompactTextString(m) }
func (*NetUserInfo) ProtoMessage()    {}
func (*NetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{1}
}
func (m *NetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetUserInfo.Unmarshal(m, b)
}
func (m *NetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetUserInfo.Marshal(b, m, deterministic)
}
func (dst *NetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetUserInfo.Merge(dst, src)
}
func (m *NetUserInfo) XXX_Size() int {
	return xxx_messageInfo_NetUserInfo.Size(m)
}
func (m *NetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetUserInfo proto.InternalMessageInfo

func (m *NetUserInfo) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetUserInfo) GetGold() int64 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *NetUserInfo) GetMoney() int64 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *NetUserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NetUserInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *NetUserInfo) GetHead() string {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return ""
}

func (m *NetUserInfo) GetIsGm() bool {
	if m != nil && m.IsGm != nil {
		return *m.IsGm
	}
	return false
}

func (m *NetUserInfo) GetJiahui() int32 {
	if m != nil && m.Jiahui != nil {
		return *m.Jiahui
	}
	return 0
}

type NetRoleVO struct {
	Guid                 *int64        `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Name                 *string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level                *int32        `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Zhanli               *int64        `protobuf:"varint,4,opt,name=zhanli" json:"zhanli,omitempty"`
	ConfigId             *int32        `protobuf:"varint,5,opt,name=configId" json:"configId,omitempty"`
	MaxHp                *int64        `protobuf:"varint,6,opt,name=maxHp" json:"maxHp,omitempty"`
	Speed                *int32        `protobuf:"varint,7,opt,name=speed" json:"speed,omitempty"`
	Leader               *int64        `protobuf:"varint,8,opt,name=leader" json:"leader,omitempty"`
	UserRoleId           *int64        `protobuf:"varint,9,opt,name=userRoleId" json:"userRoleId,omitempty"`
	RoleIndex            *int32        `protobuf:"varint,10,opt,name=roleIndex" json:"roleIndex,omitempty"`
	CurExp               *int64        `protobuf:"varint,11,opt,name=curExp" json:"curExp,omitempty"`
	StarId               *int32        `protobuf:"varint,12,opt,name=starId" json:"starId,omitempty"`
	Sex                  *int32        `protobuf:"varint,13,opt,name=sex" json:"sex,omitempty"`
	EquipVo              []*NetEquipVo `protobuf:"bytes,14,rep,name=equipVo" json:"equipVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NetRoleVO) Reset()         { *m = NetRoleVO{} }
func (m *NetRoleVO) String() string { return proto.CompactTextString(m) }
func (*NetRoleVO) ProtoMessage()    {}
func (*NetRoleVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{2}
}
func (m *NetRoleVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetRoleVO.Unmarshal(m, b)
}
func (m *NetRoleVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetRoleVO.Marshal(b, m, deterministic)
}
func (dst *NetRoleVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetRoleVO.Merge(dst, src)
}
func (m *NetRoleVO) XXX_Size() int {
	return xxx_messageInfo_NetRoleVO.Size(m)
}
func (m *NetRoleVO) XXX_DiscardUnknown() {
	xxx_messageInfo_NetRoleVO.DiscardUnknown(m)
}

var xxx_messageInfo_NetRoleVO proto.InternalMessageInfo

func (m *NetRoleVO) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetRoleVO) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NetRoleVO) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *NetRoleVO) GetZhanli() int64 {
	if m != nil && m.Zhanli != nil {
		return *m.Zhanli
	}
	return 0
}

func (m *NetRoleVO) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *NetRoleVO) GetMaxHp() int64 {
	if m != nil && m.MaxHp != nil {
		return *m.MaxHp
	}
	return 0
}

func (m *NetRoleVO) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *NetRoleVO) GetLeader() int64 {
	if m != nil && m.Leader != nil {
		return *m.Leader
	}
	return 0
}

func (m *NetRoleVO) GetUserRoleId() int64 {
	if m != nil && m.UserRoleId != nil {
		return *m.UserRoleId
	}
	return 0
}

func (m *NetRoleVO) GetRoleIndex() int32 {
	if m != nil && m.RoleIndex != nil {
		return *m.RoleIndex
	}
	return 0
}

func (m *NetRoleVO) GetCurExp() int64 {
	if m != nil && m.CurExp != nil {
		return *m.CurExp
	}
	return 0
}

func (m *NetRoleVO) GetStarId() int32 {
	if m != nil && m.StarId != nil {
		return *m.StarId
	}
	return 0
}

func (m *NetRoleVO) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *NetRoleVO) GetEquipVo() []*NetEquipVo {
	if m != nil {
		return m.EquipVo
	}
	return nil
}

type NetStageElementVO struct {
	Guid                 *int64            `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Skills               []*NetSimpleSkill `protobuf:"bytes,2,rep,name=skills" json:"skills,omitempty"`
	CurHp                *int64            `protobuf:"varint,3,opt,name=curHp" json:"curHp,omitempty"`
	ConfigId             *int32            `protobuf:"varint,4,opt,name=configId" json:"configId,omitempty"`
	Index                *int32            `protobuf:"varint,5,opt,name=index" json:"index,omitempty"`
	Type                 *int32            `protobuf:"varint,6,opt,name=type" json:"type,omitempty"`
	Batch                *int32            `protobuf:"varint,7,opt,name=batch" json:"batch,omitempty"`
	Sex                  *int32            `protobuf:"varint,8,opt,name=sex" json:"sex,omitempty"`
	MaxHp                *int64            `protobuf:"varint,9,opt,name=maxHp" json:"maxHp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NetStageElementVO) Reset()         { *m = NetStageElementVO{} }
func (m *NetStageElementVO) String() string { return proto.CompactTextString(m) }
func (*NetStageElementVO) ProtoMessage()    {}
func (*NetStageElementVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{3}
}
func (m *NetStageElementVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetStageElementVO.Unmarshal(m, b)
}
func (m *NetStageElementVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetStageElementVO.Marshal(b, m, deterministic)
}
func (dst *NetStageElementVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetStageElementVO.Merge(dst, src)
}
func (m *NetStageElementVO) XXX_Size() int {
	return xxx_messageInfo_NetStageElementVO.Size(m)
}
func (m *NetStageElementVO) XXX_DiscardUnknown() {
	xxx_messageInfo_NetStageElementVO.DiscardUnknown(m)
}

var xxx_messageInfo_NetStageElementVO proto.InternalMessageInfo

func (m *NetStageElementVO) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetStageElementVO) GetSkills() []*NetSimpleSkill {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *NetStageElementVO) GetCurHp() int64 {
	if m != nil && m.CurHp != nil {
		return *m.CurHp
	}
	return 0
}

func (m *NetStageElementVO) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *NetStageElementVO) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *NetStageElementVO) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *NetStageElementVO) GetBatch() int32 {
	if m != nil && m.Batch != nil {
		return *m.Batch
	}
	return 0
}

func (m *NetStageElementVO) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *NetStageElementVO) GetMaxHp() int64 {
	if m != nil && m.MaxHp != nil {
		return *m.MaxHp
	}
	return 0
}

type NetSimpleSkill struct {
	SkillId              *int32   `protobuf:"varint,1,opt,name=skillId" json:"skillId,omitempty"`
	Level                *int32   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetSimpleSkill) Reset()         { *m = NetSimpleSkill{} }
func (m *NetSimpleSkill) String() string { return proto.CompactTextString(m) }
func (*NetSimpleSkill) ProtoMessage()    {}
func (*NetSimpleSkill) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{4}
}
func (m *NetSimpleSkill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetSimpleSkill.Unmarshal(m, b)
}
func (m *NetSimpleSkill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetSimpleSkill.Marshal(b, m, deterministic)
}
func (dst *NetSimpleSkill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetSimpleSkill.Merge(dst, src)
}
func (m *NetSimpleSkill) XXX_Size() int {
	return xxx_messageInfo_NetSimpleSkill.Size(m)
}
func (m *NetSimpleSkill) XXX_DiscardUnknown() {
	xxx_messageInfo_NetSimpleSkill.DiscardUnknown(m)
}

var xxx_messageInfo_NetSimpleSkill proto.InternalMessageInfo

func (m *NetSimpleSkill) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *NetSimpleSkill) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type NetSkillInfo struct {
	Guid                 *int64            `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Skills               []*NetSimpleSkill `protobuf:"bytes,2,rep,name=skills" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NetSkillInfo) Reset()         { *m = NetSkillInfo{} }
func (m *NetSkillInfo) String() string { return proto.CompactTextString(m) }
func (*NetSkillInfo) ProtoMessage()    {}
func (*NetSkillInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{5}
}
func (m *NetSkillInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetSkillInfo.Unmarshal(m, b)
}
func (m *NetSkillInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetSkillInfo.Marshal(b, m, deterministic)
}
func (dst *NetSkillInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetSkillInfo.Merge(dst, src)
}
func (m *NetSkillInfo) XXX_Size() int {
	return xxx_messageInfo_NetSkillInfo.Size(m)
}
func (m *NetSkillInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetSkillInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetSkillInfo proto.InternalMessageInfo

func (m *NetSkillInfo) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetSkillInfo) GetSkills() []*NetSimpleSkill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type NetPBData struct {
	Cmd                  *int32   `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Timeline             *int32   `protobuf:"varint,3,opt,name=timeline" json:"timeline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetPBData) Reset()         { *m = NetPBData{} }
func (m *NetPBData) String() string { return proto.CompactTextString(m) }
func (*NetPBData) ProtoMessage()    {}
func (*NetPBData) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{6}
}
func (m *NetPBData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetPBData.Unmarshal(m, b)
}
func (m *NetPBData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetPBData.Marshal(b, m, deterministic)
}
func (dst *NetPBData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetPBData.Merge(dst, src)
}
func (m *NetPBData) XXX_Size() int {
	return xxx_messageInfo_NetPBData.Size(m)
}
func (m *NetPBData) XXX_DiscardUnknown() {
	xxx_messageInfo_NetPBData.DiscardUnknown(m)
}

var xxx_messageInfo_NetPBData proto.InternalMessageInfo

func (m *NetPBData) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *NetPBData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NetPBData) GetTimeline() int32 {
	if m != nil && m.Timeline != nil {
		return *m.Timeline
	}
	return 0
}

type NetHarmInfo struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	HarmTypeValue        *int32   `protobuf:"varint,2,opt,name=harmTypeValue" json:"harmTypeValue,omitempty"`
	HarmValue            *int64   `protobuf:"varint,3,opt,name=harmValue" json:"harmValue,omitempty"`
	IsDead               *bool    `protobuf:"varint,4,opt,name=isDead" json:"isDead,omitempty"`
	DdVal                *int64   `protobuf:"varint,5,opt,name=ddVal" json:"ddVal,omitempty"`
	FsVal                *int64   `protobuf:"varint,6,opt,name=fsVal" json:"fsVal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetHarmInfo) Reset()         { *m = NetHarmInfo{} }
func (m *NetHarmInfo) String() string { return proto.CompactTextString(m) }
func (*NetHarmInfo) ProtoMessage()    {}
func (*NetHarmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{7}
}
func (m *NetHarmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetHarmInfo.Unmarshal(m, b)
}
func (m *NetHarmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetHarmInfo.Marshal(b, m, deterministic)
}
func (dst *NetHarmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetHarmInfo.Merge(dst, src)
}
func (m *NetHarmInfo) XXX_Size() int {
	return xxx_messageInfo_NetHarmInfo.Size(m)
}
func (m *NetHarmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetHarmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetHarmInfo proto.InternalMessageInfo

func (m *NetHarmInfo) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetHarmInfo) GetHarmTypeValue() int32 {
	if m != nil && m.HarmTypeValue != nil {
		return *m.HarmTypeValue
	}
	return 0
}

func (m *NetHarmInfo) GetHarmValue() int64 {
	if m != nil && m.HarmValue != nil {
		return *m.HarmValue
	}
	return 0
}

func (m *NetHarmInfo) GetIsDead() bool {
	if m != nil && m.IsDead != nil {
		return *m.IsDead
	}
	return false
}

func (m *NetHarmInfo) GetDdVal() int64 {
	if m != nil && m.DdVal != nil {
		return *m.DdVal
	}
	return 0
}

func (m *NetHarmInfo) GetFsVal() int64 {
	if m != nil && m.FsVal != nil {
		return *m.FsVal
	}
	return 0
}

type NetAttrInfos struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetAttrInfos) Reset()         { *m = NetAttrInfos{} }
func (m *NetAttrInfos) String() string { return proto.CompactTextString(m) }
func (*NetAttrInfos) ProtoMessage()    {}
func (*NetAttrInfos) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{8}
}
func (m *NetAttrInfos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetAttrInfos.Unmarshal(m, b)
}
func (m *NetAttrInfos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetAttrInfos.Marshal(b, m, deterministic)
}
func (dst *NetAttrInfos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetAttrInfos.Merge(dst, src)
}
func (m *NetAttrInfos) XXX_Size() int {
	return xxx_messageInfo_NetAttrInfos.Size(m)
}
func (m *NetAttrInfos) XXX_DiscardUnknown() {
	xxx_messageInfo_NetAttrInfos.DiscardUnknown(m)
}

var xxx_messageInfo_NetAttrInfos proto.InternalMessageInfo

func (m *NetAttrInfos) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *NetAttrInfos) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type KeyValue struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{9}
}
func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (dst *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(dst, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type NetItemVO struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Count                *int32   `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	TplId                *string  `protobuf:"bytes,3,opt,name=tplId" json:"tplId,omitempty"`
	ExpireTime           *int64   `protobuf:"varint,4,opt,name=expireTime" json:"expireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetItemVO) Reset()         { *m = NetItemVO{} }
func (m *NetItemVO) String() string { return proto.CompactTextString(m) }
func (*NetItemVO) ProtoMessage()    {}
func (*NetItemVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{10}
}
func (m *NetItemVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetItemVO.Unmarshal(m, b)
}
func (m *NetItemVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetItemVO.Marshal(b, m, deterministic)
}
func (dst *NetItemVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetItemVO.Merge(dst, src)
}
func (m *NetItemVO) XXX_Size() int {
	return xxx_messageInfo_NetItemVO.Size(m)
}
func (m *NetItemVO) XXX_DiscardUnknown() {
	xxx_messageInfo_NetItemVO.DiscardUnknown(m)
}

var xxx_messageInfo_NetItemVO proto.InternalMessageInfo

func (m *NetItemVO) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *NetItemVO) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *NetItemVO) GetTplId() string {
	if m != nil && m.TplId != nil {
		return *m.TplId
	}
	return ""
}

func (m *NetItemVO) GetExpireTime() int64 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

type NetEquipVo struct {
	ItemGuid             *int64   `protobuf:"varint,1,opt,name=itemGuid" json:"itemGuid,omitempty"`
	EquipSlot            *int32   `protobuf:"varint,2,opt,name=equipSlot" json:"equipSlot,omitempty"`
	ItemCfgId            *string  `protobuf:"bytes,3,opt,name=itemCfgId" json:"itemCfgId,omitempty"`
	QhLevel              *int32   `protobuf:"varint,4,opt,name=qhLevel" json:"qhLevel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetEquipVo) Reset()         { *m = NetEquipVo{} }
func (m *NetEquipVo) String() string { return proto.CompactTextString(m) }
func (*NetEquipVo) ProtoMessage()    {}
func (*NetEquipVo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{11}
}
func (m *NetEquipVo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetEquipVo.Unmarshal(m, b)
}
func (m *NetEquipVo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetEquipVo.Marshal(b, m, deterministic)
}
func (dst *NetEquipVo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetEquipVo.Merge(dst, src)
}
func (m *NetEquipVo) XXX_Size() int {
	return xxx_messageInfo_NetEquipVo.Size(m)
}
func (m *NetEquipVo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetEquipVo.DiscardUnknown(m)
}

var xxx_messageInfo_NetEquipVo proto.InternalMessageInfo

func (m *NetEquipVo) GetItemGuid() int64 {
	if m != nil && m.ItemGuid != nil {
		return *m.ItemGuid
	}
	return 0
}

func (m *NetEquipVo) GetEquipSlot() int32 {
	if m != nil && m.EquipSlot != nil {
		return *m.EquipSlot
	}
	return 0
}

func (m *NetEquipVo) GetItemCfgId() string {
	if m != nil && m.ItemCfgId != nil {
		return *m.ItemCfgId
	}
	return ""
}

func (m *NetEquipVo) GetQhLevel() int32 {
	if m != nil && m.QhLevel != nil {
		return *m.QhLevel
	}
	return 0
}

type NetEliteInfo struct {
	CfgId                *int32   `protobuf:"varint,1,opt,name=cfgId" json:"cfgId,omitempty"`
	Star                 *int32   `protobuf:"varint,2,opt,name=star" json:"star,omitempty"`
	ResetTimes           *int32   `protobuf:"varint,3,opt,name=resetTimes" json:"resetTimes,omitempty"`
	FreeSDTimes          *int32   `protobuf:"varint,4,opt,name=freeSDTimes" json:"freeSDTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetEliteInfo) Reset()         { *m = NetEliteInfo{} }
func (m *NetEliteInfo) String() string { return proto.CompactTextString(m) }
func (*NetEliteInfo) ProtoMessage()    {}
func (*NetEliteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{12}
}
func (m *NetEliteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetEliteInfo.Unmarshal(m, b)
}
func (m *NetEliteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetEliteInfo.Marshal(b, m, deterministic)
}
func (dst *NetEliteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetEliteInfo.Merge(dst, src)
}
func (m *NetEliteInfo) XXX_Size() int {
	return xxx_messageInfo_NetEliteInfo.Size(m)
}
func (m *NetEliteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetEliteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetEliteInfo proto.InternalMessageInfo

func (m *NetEliteInfo) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

func (m *NetEliteInfo) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func (m *NetEliteInfo) GetResetTimes() int32 {
	if m != nil && m.ResetTimes != nil {
		return *m.ResetTimes
	}
	return 0
}

func (m *NetEliteInfo) GetFreeSDTimes() int32 {
	if m != nil && m.FreeSDTimes != nil {
		return *m.FreeSDTimes
	}
	return 0
}

type NetCaiLiaoInfo struct {
	FbType               *int32   `protobuf:"varint,1,opt,name=fbType" json:"fbType,omitempty"`
	FbId                 *int32   `protobuf:"varint,2,opt,name=fbId" json:"fbId,omitempty"`
	Count                *int32   `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
	Buycount             *int32   `protobuf:"varint,4,opt,name=buycount" json:"buycount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetCaiLiaoInfo) Reset()         { *m = NetCaiLiaoInfo{} }
func (m *NetCaiLiaoInfo) String() string { return proto.CompactTextString(m) }
func (*NetCaiLiaoInfo) ProtoMessage()    {}
func (*NetCaiLiaoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{13}
}
func (m *NetCaiLiaoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetCaiLiaoInfo.Unmarshal(m, b)
}
func (m *NetCaiLiaoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetCaiLiaoInfo.Marshal(b, m, deterministic)
}
func (dst *NetCaiLiaoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetCaiLiaoInfo.Merge(dst, src)
}
func (m *NetCaiLiaoInfo) XXX_Size() int {
	return xxx_messageInfo_NetCaiLiaoInfo.Size(m)
}
func (m *NetCaiLiaoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetCaiLiaoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetCaiLiaoInfo proto.InternalMessageInfo

func (m *NetCaiLiaoInfo) GetFbType() int32 {
	if m != nil && m.FbType != nil {
		return *m.FbType
	}
	return 0
}

func (m *NetCaiLiaoInfo) GetFbId() int32 {
	if m != nil && m.FbId != nil {
		return *m.FbId
	}
	return 0
}

func (m *NetCaiLiaoInfo) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *NetCaiLiaoInfo) GetBuycount() int32 {
	if m != nil && m.Buycount != nil {
		return *m.Buycount
	}
	return 0
}

type NetItemVOs struct {
	Items                []*NetItemVO `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NetItemVOs) Reset()         { *m = NetItemVOs{} }
func (m *NetItemVOs) String() string { return proto.CompactTextString(m) }
func (*NetItemVOs) ProtoMessage()    {}
func (*NetItemVOs) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{14}
}
func (m *NetItemVOs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetItemVOs.Unmarshal(m, b)
}
func (m *NetItemVOs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetItemVOs.Marshal(b, m, deterministic)
}
func (dst *NetItemVOs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetItemVOs.Merge(dst, src)
}
func (m *NetItemVOs) XXX_Size() int {
	return xxx_messageInfo_NetItemVOs.Size(m)
}
func (m *NetItemVOs) XXX_DiscardUnknown() {
	xxx_messageInfo_NetItemVOs.DiscardUnknown(m)
}

var xxx_messageInfo_NetItemVOs proto.InternalMessageInfo

func (m *NetItemVOs) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

type NetFubenInfo struct {
	CfgId                *int32   `protobuf:"varint,1,opt,name=cfgId" json:"cfgId,omitempty"`
	Star                 *int32   `protobuf:"varint,2,opt,name=star" json:"star,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetFubenInfo) Reset()         { *m = NetFubenInfo{} }
func (m *NetFubenInfo) String() string { return proto.CompactTextString(m) }
func (*NetFubenInfo) ProtoMessage()    {}
func (*NetFubenInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_BaseVO_c8aa2d0c32603712, []int{15}
}
func (m *NetFubenInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetFubenInfo.Unmarshal(m, b)
}
func (m *NetFubenInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetFubenInfo.Marshal(b, m, deterministic)
}
func (dst *NetFubenInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetFubenInfo.Merge(dst, src)
}
func (m *NetFubenInfo) XXX_Size() int {
	return xxx_messageInfo_NetFubenInfo.Size(m)
}
func (m *NetFubenInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NetFubenInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NetFubenInfo proto.InternalMessageInfo

func (m *NetFubenInfo) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

func (m *NetFubenInfo) GetStar() int32 {
	if m != nil && m.Star != nil {
		return *m.Star
	}
	return 0
}

func init() {
	proto.RegisterType((*Code)(nil), "message.Code")
	proto.RegisterType((*NetUserInfo)(nil), "message.NetUserInfo")
	proto.RegisterType((*NetRoleVO)(nil), "message.NetRoleVO")
	proto.RegisterType((*NetStageElementVO)(nil), "message.NetStageElementVO")
	proto.RegisterType((*NetSimpleSkill)(nil), "message.NetSimpleSkill")
	proto.RegisterType((*NetSkillInfo)(nil), "message.NetSkillInfo")
	proto.RegisterType((*NetPBData)(nil), "message.NetPBData")
	proto.RegisterType((*NetHarmInfo)(nil), "message.NetHarmInfo")
	proto.RegisterType((*NetAttrInfos)(nil), "message.NetAttrInfos")
	proto.RegisterType((*KeyValue)(nil), "message.KeyValue")
	proto.RegisterType((*NetItemVO)(nil), "message.NetItemVO")
	proto.RegisterType((*NetEquipVo)(nil), "message.NetEquipVo")
	proto.RegisterType((*NetEliteInfo)(nil), "message.NetEliteInfo")
	proto.RegisterType((*NetCaiLiaoInfo)(nil), "message.NetCaiLiaoInfo")
	proto.RegisterType((*NetItemVOs)(nil), "message.NetItemVOs")
	proto.RegisterType((*NetFubenInfo)(nil), "message.NetFubenInfo")
	proto.RegisterEnum("message.ElementType", ElementType_name, ElementType_value)
}

func init() { proto.RegisterFile("BaseVO.proto", fileDescriptor_BaseVO_c8aa2d0c32603712) }

var fileDescriptor_BaseVO_c8aa2d0c32603712 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x8e, 0x23, 0x35,
	0x10, 0x56, 0xa7, 0x93, 0x4c, 0xe2, 0xcc, 0xae, 0x86, 0x5e, 0x98, 0xb5, 0x56, 0x08, 0x45, 0x2d,
	0x0e, 0x11, 0x12, 0x83, 0x34, 0x87, 0x15, 0x07, 0x0e, 0x30, 0x3f, 0xec, 0x44, 0xec, 0x66, 0x91,
	0x33, 0xe4, 0x8a, 0x9c, 0xb8, 0x92, 0x98, 0xe9, 0xbf, 0x6d, 0xbb, 0x57, 0xc9, 0x1e, 0x78, 0x1f,
	0x1e, 0x80, 0xf7, 0x42, 0x3c, 0x01, 0xaa, 0xb2, 0x3b, 0xdd, 0x23, 0x88, 0xc4, 0xde, 0xea, 0xfb,
	0xba, 0x6c, 0x7f, 0xf5, 0xb9, 0xca, 0x6a, 0x76, 0x7a, 0x25, 0x0d, 0x2c, 0xde, 0x5e, 0x14, 0x65,
	0x6e, 0xf3, 0xe8, 0x24, 0x05, 0x63, 0xe4, 0x06, 0xe2, 0x4b, 0xd6, 0xbd, 0xce, 0x15, 0x44, 0x11,
	0xeb, 0xae, 0x72, 0x05, 0x3c, 0x18, 0x07, 0x93, 0x9e, 0xa0, 0x38, 0x3a, 0x67, 0xfd, 0x42, 0x96,
	0x32, 0x35, 0xbc, 0x33, 0x0e, 0x27, 0x43, 0xe1, 0x51, 0xfc, 0x67, 0xc0, 0x46, 0x33, 0xb0, 0xbf,
	0x18, 0x28, 0xa7, 0xd9, 0x3a, 0xc7, 0xb5, 0x9b, 0x4a, 0x2b, 0x5a, 0x1b, 0x0a, 0x8a, 0x89, 0xcb,
	0x13, 0xc5, 0x3b, 0x9e, 0xcb, 0x13, 0x15, 0x7d, 0xca, 0x7a, 0x69, 0x9e, 0xc1, 0x9e, 0x87, 0x44,
	0x3a, 0x80, 0x99, 0x99, 0x4c, 0x81, 0x77, 0xc7, 0xc1, 0x64, 0x28, 0x28, 0xc6, 0xcc, 0x04, 0xde,
	0x43, 0xc2, 0x7b, 0x24, 0xc7, 0x01, 0xcc, 0xdc, 0x82, 0x54, 0xbc, 0xef, 0x32, 0x31, 0x46, 0x4e,
	0x9b, 0x57, 0x29, 0x3f, 0x19, 0x07, 0x93, 0x81, 0xa0, 0x18, 0x75, 0xff, 0xa6, 0xe5, 0xb6, 0xd2,
	0x7c, 0x40, 0xcb, 0x3d, 0x8a, 0xff, 0xea, 0xb0, 0xe1, 0x0c, 0xac, 0xc8, 0x13, 0x58, 0xbc, 0x3d,
	0xa6, 0x9a, 0xb4, 0x74, 0xfe, 0x4b, 0x4b, 0xd8, 0xd6, 0x72, 0xce, 0xfa, 0x1f, 0xb6, 0x32, 0x4b,
	0x34, 0xe9, 0x0e, 0x85, 0x47, 0xd1, 0x0b, 0x36, 0x58, 0xe5, 0xd9, 0x5a, 0x6f, 0xa6, 0xca, 0x8b,
	0x3f, 0x60, 0xaa, 0x5f, 0xee, 0xee, 0x0a, 0x2a, 0x00, 0xeb, 0x47, 0x80, 0xac, 0x29, 0x00, 0x14,
	0x95, 0xd0, 0x13, 0x0e, 0xe0, 0xfe, 0x09, 0x48, 0x05, 0x25, 0xd5, 0x10, 0x0a, 0x8f, 0xa2, 0x2f,
	0x18, 0xab, 0x0c, 0x94, 0x58, 0xc3, 0x54, 0xf1, 0x21, 0x7d, 0x6b, 0x31, 0xd1, 0xe7, 0x6c, 0x58,
	0x62, 0x94, 0x29, 0xd8, 0x71, 0x46, 0x3b, 0x36, 0x04, 0xee, 0xba, 0xaa, 0xca, 0xdb, 0x5d, 0xc1,
	0x47, 0x6e, 0x57, 0x87, 0x90, 0x37, 0x56, 0x96, 0x53, 0xc5, 0x4f, 0x9d, 0x63, 0x0e, 0x45, 0x67,
	0x2c, 0x34, 0xb0, 0xe3, 0x4f, 0x88, 0xc4, 0x30, 0xfa, 0x9a, 0x9d, 0xc0, 0xbb, 0x4a, 0x17, 0x8b,
	0x9c, 0x3f, 0x1d, 0x87, 0x93, 0xd1, 0xe5, 0xb3, 0x0b, 0xdf, 0x4a, 0x17, 0x33, 0xb0, 0xb7, 0xee,
	0x93, 0xa8, 0x73, 0xe2, 0xbf, 0x03, 0xf6, 0xc9, 0x0c, 0xec, 0xdc, 0xca, 0x0d, 0xdc, 0x26, 0x90,
	0x42, 0x66, 0x8f, 0x58, 0xff, 0x0d, 0xeb, 0x9b, 0x07, 0x9d, 0x24, 0xae, 0xd9, 0x46, 0x97, 0xcf,
	0xdb, 0xfb, 0xce, 0x75, 0x5a, 0x24, 0x30, 0xc7, 0xef, 0xc2, 0xa7, 0xa1, 0x6f, 0xab, 0xaa, 0xbc,
	0x2b, 0xea, 0x6e, 0x22, 0xf0, 0xc8, 0xff, 0xee, 0xbf, 0xfd, 0xd7, 0xe4, 0x8b, 0xef, 0x2a, 0x02,
	0x28, 0xc6, 0xee, 0x0b, 0xa0, 0x4b, 0xe9, 0x09, 0x8a, 0x31, 0x73, 0x29, 0xed, 0x6a, 0x5b, 0xdf,
	0x09, 0x81, 0xda, 0x8d, 0x41, 0xe3, 0xc6, 0xe1, 0x46, 0x87, 0xad, 0x1b, 0x8d, 0xbf, 0x67, 0x4f,
	0x1f, 0x6b, 0x8e, 0x38, 0x3b, 0x21, 0xd5, 0x53, 0xe5, 0x07, 0xac, 0x86, 0x4d, 0x77, 0x75, 0x5a,
	0xdd, 0x15, 0xcf, 0xd9, 0x29, 0xee, 0x40, 0x39, 0xc7, 0x26, 0xec, 0x63, 0x0d, 0x8b, 0xdf, 0x50,
	0xf7, 0xff, 0x7c, 0x75, 0x23, 0xad, 0xc4, 0x5a, 0x56, 0x69, 0xad, 0x06, 0x43, 0x3c, 0x43, 0x49,
	0x2b, 0x49, 0xc8, 0xa9, 0xa0, 0x18, 0xdd, 0xb4, 0x3a, 0x85, 0x44, 0x67, 0xe0, 0xdb, 0xff, 0x80,
	0xe3, 0x3f, 0xdc, 0x2b, 0x70, 0x27, 0xcb, 0xf4, 0xa8, 0xc6, 0x2f, 0xd9, 0x93, 0xad, 0x2c, 0xd3,
	0xfb, 0x7d, 0x01, 0x0b, 0x99, 0x54, 0xe0, 0xab, 0x7c, 0x4c, 0x62, 0xcf, 0x22, 0xe1, 0x32, 0xdc,
	0x6d, 0x36, 0x04, 0xf6, 0xa6, 0x36, 0x37, 0x38, 0xf7, 0x5d, 0x9a, 0x71, 0x8f, 0xd0, 0x39, 0xa5,
	0x16, 0xd2, 0xbd, 0x11, 0xa1, 0x70, 0x00, 0xd9, 0xb5, 0x41, 0xd6, 0xcf, 0x18, 0x81, 0xf8, 0x25,
	0xf9, 0xf9, 0x83, 0xb5, 0xf4, 0x60, 0x19, 0xac, 0xfe, 0x01, 0xf6, 0x24, 0x75, 0x28, 0x30, 0xc4,
	0x75, 0xef, 0x0f, 0x0a, 0x87, 0xc2, 0x81, 0xf8, 0x92, 0x0d, 0x7e, 0x82, 0xbd, 0xd3, 0xf1, 0x7f,
	0xd7, 0x3c, 0x90, 0xcd, 0x53, 0x0b, 0xe9, 0x91, 0x4e, 0xc7, 0xc6, 0xcd, 0xab, 0xcc, 0xd6, 0x57,
	0x4e, 0x00, 0x59, 0x5b, 0x60, 0x83, 0x84, 0x6e, 0x33, 0x02, 0x38, 0xee, 0xb0, 0x2b, 0x74, 0x09,
	0xf7, 0xda, 0x3f, 0x91, 0xa1, 0x68, 0x31, 0xf1, 0xef, 0x8c, 0x35, 0x63, 0x87, 0xd7, 0xa5, 0x2d,
	0xa4, 0xaf, 0x9a, 0x13, 0x0f, 0x18, 0x4d, 0xa6, 0xa1, 0x9c, 0x27, 0x79, 0x7d, 0x72, 0x43, 0xe0,
	0x57, 0xcc, 0xbc, 0x5e, 0x6f, 0x0e, 0x0a, 0x1a, 0x02, 0xdb, 0xf7, 0xdd, 0xf6, 0x35, 0xb5, 0xa9,
	0x9b, 0xa9, 0x1a, 0xc6, 0x1f, 0xc8, 0xd8, 0xdb, 0x44, 0x5b, 0xa0, 0x26, 0xc0, 0xda, 0x68, 0x8f,
	0xc0, 0xd7, 0x46, 0xeb, 0x23, 0xd6, 0xc5, 0x07, 0xc5, 0x1f, 0x4b, 0x31, 0x56, 0x56, 0x82, 0x01,
	0x8b, 0x65, 0x18, 0xdf, 0x5c, 0x2d, 0x26, 0x1a, 0xb3, 0xd1, 0xba, 0x04, 0x98, 0xdf, 0xb8, 0x04,
	0x77, 0x6e, 0x9b, 0x8a, 0x33, 0x1a, 0xb3, 0x6b, 0xa9, 0x5f, 0x6b, 0x99, 0xd3, 0xe9, 0xe7, 0xac,
	0xbf, 0x5e, 0x62, 0x5f, 0xf9, 0xe3, 0x3d, 0xc2, 0xf3, 0xd7, 0xcb, 0xa9, 0xaa, 0xcf, 0xc7, 0xb8,
	0xb9, 0x85, 0xb0, 0x7d, 0x0b, 0x2f, 0xd8, 0x60, 0x59, 0xed, 0xdd, 0x07, 0xff, 0x7c, 0xd4, 0x38,
	0x7e, 0x49, 0x5e, 0xbb, 0x8b, 0x35, 0xd1, 0x84, 0xf5, 0xd0, 0x20, 0xc3, 0x03, 0x9a, 0xbe, 0xa8,
	0x3d, 0x7d, 0x2e, 0x47, 0xb8, 0x84, 0xf8, 0x5b, 0xf2, 0xe8, 0xc7, 0x6a, 0x09, 0xd9, 0xc7, 0x79,
	0xf4, 0xd5, 0x77, 0x6c, 0xe4, 0x1f, 0xcd, 0x7b, 0xf7, 0x2a, 0x9d, 0xb5, 0xe0, 0xaf, 0xf8, 0xe2,
	0x9f, 0x05, 0xd1, 0x73, 0xf6, 0xac, 0xcd, 0xbe, 0xc9, 0x33, 0x63, 0xa1, 0x3c, 0xeb, 0x5c, 0x7d,
	0xc6, 0x46, 0xab, 0x3c, 0xad, 0x75, 0x5d, 0xf5, 0xdd, 0x0f, 0xc0, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0x17, 0xce, 0x1f, 0x09, 0x08, 0x00, 0x00,
}
