// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CaiLiaoZoneMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CaiLiaoZoneInfo_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaiLiaoZoneInfo_C) Reset()         { *m = CaiLiaoZoneInfo_C{} }
func (m *CaiLiaoZoneInfo_C) String() string { return proto.CompactTextString(m) }
func (*CaiLiaoZoneInfo_C) ProtoMessage()    {}
func (*CaiLiaoZoneInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{0}
}
func (m *CaiLiaoZoneInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaiLiaoZoneInfo_C.Unmarshal(m, b)
}
func (m *CaiLiaoZoneInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaiLiaoZoneInfo_C.Marshal(b, m, deterministic)
}
func (dst *CaiLiaoZoneInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaiLiaoZoneInfo_C.Merge(dst, src)
}
func (m *CaiLiaoZoneInfo_C) XXX_Size() int {
	return xxx_messageInfo_CaiLiaoZoneInfo_C.Size(m)
}
func (m *CaiLiaoZoneInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_CaiLiaoZoneInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_CaiLiaoZoneInfo_C proto.InternalMessageInfo

type CaiLiaoZoneInfo_S struct {
	Code                 *Code             `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	CaiLiaoInfo          []*NetCaiLiaoInfo `protobuf:"bytes,2,rep,name=caiLiaoInfo" json:"caiLiaoInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CaiLiaoZoneInfo_S) Reset()         { *m = CaiLiaoZoneInfo_S{} }
func (m *CaiLiaoZoneInfo_S) String() string { return proto.CompactTextString(m) }
func (*CaiLiaoZoneInfo_S) ProtoMessage()    {}
func (*CaiLiaoZoneInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{1}
}
func (m *CaiLiaoZoneInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaiLiaoZoneInfo_S.Unmarshal(m, b)
}
func (m *CaiLiaoZoneInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaiLiaoZoneInfo_S.Marshal(b, m, deterministic)
}
func (dst *CaiLiaoZoneInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaiLiaoZoneInfo_S.Merge(dst, src)
}
func (m *CaiLiaoZoneInfo_S) XXX_Size() int {
	return xxx_messageInfo_CaiLiaoZoneInfo_S.Size(m)
}
func (m *CaiLiaoZoneInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_CaiLiaoZoneInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_CaiLiaoZoneInfo_S proto.InternalMessageInfo

func (m *CaiLiaoZoneInfo_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CaiLiaoZoneInfo_S) GetCaiLiaoInfo() []*NetCaiLiaoInfo {
	if m != nil {
		return m.CaiLiaoInfo
	}
	return nil
}

type EnterCaiLiaoZone_C struct {
	FbType               *int32   `protobuf:"varint,1,opt,name=fbType" json:"fbType,omitempty"`
	FbId                 *int32   `protobuf:"varint,2,opt,name=fbId" json:"fbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterCaiLiaoZone_C) Reset()         { *m = EnterCaiLiaoZone_C{} }
func (m *EnterCaiLiaoZone_C) String() string { return proto.CompactTextString(m) }
func (*EnterCaiLiaoZone_C) ProtoMessage()    {}
func (*EnterCaiLiaoZone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{2}
}
func (m *EnterCaiLiaoZone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterCaiLiaoZone_C.Unmarshal(m, b)
}
func (m *EnterCaiLiaoZone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterCaiLiaoZone_C.Marshal(b, m, deterministic)
}
func (dst *EnterCaiLiaoZone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterCaiLiaoZone_C.Merge(dst, src)
}
func (m *EnterCaiLiaoZone_C) XXX_Size() int {
	return xxx_messageInfo_EnterCaiLiaoZone_C.Size(m)
}
func (m *EnterCaiLiaoZone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterCaiLiaoZone_C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterCaiLiaoZone_C proto.InternalMessageInfo

func (m *EnterCaiLiaoZone_C) GetFbType() int32 {
	if m != nil && m.FbType != nil {
		return *m.FbType
	}
	return 0
}

func (m *EnterCaiLiaoZone_C) GetFbId() int32 {
	if m != nil && m.FbId != nil {
		return *m.FbId
	}
	return 0
}

type EnterCaiLiaoZone_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterCaiLiaoZone_S) Reset()         { *m = EnterCaiLiaoZone_S{} }
func (m *EnterCaiLiaoZone_S) String() string { return proto.CompactTextString(m) }
func (*EnterCaiLiaoZone_S) ProtoMessage()    {}
func (*EnterCaiLiaoZone_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{3}
}
func (m *EnterCaiLiaoZone_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterCaiLiaoZone_S.Unmarshal(m, b)
}
func (m *EnterCaiLiaoZone_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterCaiLiaoZone_S.Marshal(b, m, deterministic)
}
func (dst *EnterCaiLiaoZone_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterCaiLiaoZone_S.Merge(dst, src)
}
func (m *EnterCaiLiaoZone_S) XXX_Size() int {
	return xxx_messageInfo_EnterCaiLiaoZone_S.Size(m)
}
func (m *EnterCaiLiaoZone_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterCaiLiaoZone_S.DiscardUnknown(m)
}

var xxx_messageInfo_EnterCaiLiaoZone_S proto.InternalMessageInfo

func (m *EnterCaiLiaoZone_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type CaiLiaoZoneResult_S struct {
	Iswin                *bool           `protobuf:"varint,1,opt,name=iswin" json:"iswin,omitempty"`
	Items                []*NetItemVO    `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	CaiLiaoInfo          *NetCaiLiaoInfo `protobuf:"bytes,3,opt,name=caiLiaoInfo" json:"caiLiaoInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CaiLiaoZoneResult_S) Reset()         { *m = CaiLiaoZoneResult_S{} }
func (m *CaiLiaoZoneResult_S) String() string { return proto.CompactTextString(m) }
func (*CaiLiaoZoneResult_S) ProtoMessage()    {}
func (*CaiLiaoZoneResult_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{4}
}
func (m *CaiLiaoZoneResult_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaiLiaoZoneResult_S.Unmarshal(m, b)
}
func (m *CaiLiaoZoneResult_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaiLiaoZoneResult_S.Marshal(b, m, deterministic)
}
func (dst *CaiLiaoZoneResult_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaiLiaoZoneResult_S.Merge(dst, src)
}
func (m *CaiLiaoZoneResult_S) XXX_Size() int {
	return xxx_messageInfo_CaiLiaoZoneResult_S.Size(m)
}
func (m *CaiLiaoZoneResult_S) XXX_DiscardUnknown() {
	xxx_messageInfo_CaiLiaoZoneResult_S.DiscardUnknown(m)
}

var xxx_messageInfo_CaiLiaoZoneResult_S proto.InternalMessageInfo

func (m *CaiLiaoZoneResult_S) GetIswin() bool {
	if m != nil && m.Iswin != nil {
		return *m.Iswin
	}
	return false
}

func (m *CaiLiaoZoneResult_S) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *CaiLiaoZoneResult_S) GetCaiLiaoInfo() *NetCaiLiaoInfo {
	if m != nil {
		return m.CaiLiaoInfo
	}
	return nil
}

type SaoDangCaiLiaoZone_C struct {
	FbType               *int32   `protobuf:"varint,1,opt,name=fbType" json:"fbType,omitempty"`
	FbId                 *int32   `protobuf:"varint,2,opt,name=fbId" json:"fbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaoDangCaiLiaoZone_C) Reset()         { *m = SaoDangCaiLiaoZone_C{} }
func (m *SaoDangCaiLiaoZone_C) String() string { return proto.CompactTextString(m) }
func (*SaoDangCaiLiaoZone_C) ProtoMessage()    {}
func (*SaoDangCaiLiaoZone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{5}
}
func (m *SaoDangCaiLiaoZone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaoDangCaiLiaoZone_C.Unmarshal(m, b)
}
func (m *SaoDangCaiLiaoZone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaoDangCaiLiaoZone_C.Marshal(b, m, deterministic)
}
func (dst *SaoDangCaiLiaoZone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaoDangCaiLiaoZone_C.Merge(dst, src)
}
func (m *SaoDangCaiLiaoZone_C) XXX_Size() int {
	return xxx_messageInfo_SaoDangCaiLiaoZone_C.Size(m)
}
func (m *SaoDangCaiLiaoZone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SaoDangCaiLiaoZone_C.DiscardUnknown(m)
}

var xxx_messageInfo_SaoDangCaiLiaoZone_C proto.InternalMessageInfo

func (m *SaoDangCaiLiaoZone_C) GetFbType() int32 {
	if m != nil && m.FbType != nil {
		return *m.FbType
	}
	return 0
}

func (m *SaoDangCaiLiaoZone_C) GetFbId() int32 {
	if m != nil && m.FbId != nil {
		return *m.FbId
	}
	return 0
}

type SaoDangCaiLiaoZone_S struct {
	Code                 *Code           `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Items                []*NetItemVO    `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	CaiLiaoInfo          *NetCaiLiaoInfo `protobuf:"bytes,3,opt,name=caiLiaoInfo" json:"caiLiaoInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SaoDangCaiLiaoZone_S) Reset()         { *m = SaoDangCaiLiaoZone_S{} }
func (m *SaoDangCaiLiaoZone_S) String() string { return proto.CompactTextString(m) }
func (*SaoDangCaiLiaoZone_S) ProtoMessage()    {}
func (*SaoDangCaiLiaoZone_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{6}
}
func (m *SaoDangCaiLiaoZone_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaoDangCaiLiaoZone_S.Unmarshal(m, b)
}
func (m *SaoDangCaiLiaoZone_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaoDangCaiLiaoZone_S.Marshal(b, m, deterministic)
}
func (dst *SaoDangCaiLiaoZone_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaoDangCaiLiaoZone_S.Merge(dst, src)
}
func (m *SaoDangCaiLiaoZone_S) XXX_Size() int {
	return xxx_messageInfo_SaoDangCaiLiaoZone_S.Size(m)
}
func (m *SaoDangCaiLiaoZone_S) XXX_DiscardUnknown() {
	xxx_messageInfo_SaoDangCaiLiaoZone_S.DiscardUnknown(m)
}

var xxx_messageInfo_SaoDangCaiLiaoZone_S proto.InternalMessageInfo

func (m *SaoDangCaiLiaoZone_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SaoDangCaiLiaoZone_S) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SaoDangCaiLiaoZone_S) GetCaiLiaoInfo() *NetCaiLiaoInfo {
	if m != nil {
		return m.CaiLiaoInfo
	}
	return nil
}

type CaiLiaoZoneExit_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaiLiaoZoneExit_C) Reset()         { *m = CaiLiaoZoneExit_C{} }
func (m *CaiLiaoZoneExit_C) String() string { return proto.CompactTextString(m) }
func (*CaiLiaoZoneExit_C) ProtoMessage()    {}
func (*CaiLiaoZoneExit_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{7}
}
func (m *CaiLiaoZoneExit_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaiLiaoZoneExit_C.Unmarshal(m, b)
}
func (m *CaiLiaoZoneExit_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaiLiaoZoneExit_C.Marshal(b, m, deterministic)
}
func (dst *CaiLiaoZoneExit_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaiLiaoZoneExit_C.Merge(dst, src)
}
func (m *CaiLiaoZoneExit_C) XXX_Size() int {
	return xxx_messageInfo_CaiLiaoZoneExit_C.Size(m)
}
func (m *CaiLiaoZoneExit_C) XXX_DiscardUnknown() {
	xxx_messageInfo_CaiLiaoZoneExit_C.DiscardUnknown(m)
}

var xxx_messageInfo_CaiLiaoZoneExit_C proto.InternalMessageInfo

type CaiLiaoZoneExit_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CaiLiaoZoneExit_S) Reset()         { *m = CaiLiaoZoneExit_S{} }
func (m *CaiLiaoZoneExit_S) String() string { return proto.CompactTextString(m) }
func (*CaiLiaoZoneExit_S) ProtoMessage()    {}
func (*CaiLiaoZoneExit_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b, []int{8}
}
func (m *CaiLiaoZoneExit_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaiLiaoZoneExit_S.Unmarshal(m, b)
}
func (m *CaiLiaoZoneExit_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaiLiaoZoneExit_S.Marshal(b, m, deterministic)
}
func (dst *CaiLiaoZoneExit_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaiLiaoZoneExit_S.Merge(dst, src)
}
func (m *CaiLiaoZoneExit_S) XXX_Size() int {
	return xxx_messageInfo_CaiLiaoZoneExit_S.Size(m)
}
func (m *CaiLiaoZoneExit_S) XXX_DiscardUnknown() {
	xxx_messageInfo_CaiLiaoZoneExit_S.DiscardUnknown(m)
}

var xxx_messageInfo_CaiLiaoZoneExit_S proto.InternalMessageInfo

func (m *CaiLiaoZoneExit_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterType((*CaiLiaoZoneInfo_C)(nil), "message.CaiLiaoZoneInfo_C")
	proto.RegisterType((*CaiLiaoZoneInfo_S)(nil), "message.CaiLiaoZoneInfo_S")
	proto.RegisterType((*EnterCaiLiaoZone_C)(nil), "message.EnterCaiLiaoZone_C")
	proto.RegisterType((*EnterCaiLiaoZone_S)(nil), "message.EnterCaiLiaoZone_S")
	proto.RegisterType((*CaiLiaoZoneResult_S)(nil), "message.CaiLiaoZoneResult_S")
	proto.RegisterType((*SaoDangCaiLiaoZone_C)(nil), "message.SaoDangCaiLiaoZone_C")
	proto.RegisterType((*SaoDangCaiLiaoZone_S)(nil), "message.SaoDangCaiLiaoZone_S")
	proto.RegisterType((*CaiLiaoZoneExit_C)(nil), "message.CaiLiaoZoneExit_C")
	proto.RegisterType((*CaiLiaoZoneExit_S)(nil), "message.CaiLiaoZoneExit_S")
}

func init() {
	proto.RegisterFile("CaiLiaoZoneMsg.proto", fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b)
}

var fileDescriptor_CaiLiaoZoneMsg_9585791d70597b2b = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0x4e, 0xcc, 0xf4,
	0xc9, 0x4c, 0xcc, 0x8f, 0xca, 0xcf, 0x4b, 0xf5, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d,
	0xf3, 0x87, 0x08, 0x2b, 0x09, 0x73, 0x09, 0x22, 0x29, 0xf7, 0xcc, 0x4b, 0xcb, 0x8f, 0x77, 0x56,
	0x2a, 0xc4, 0x14, 0x0c, 0x16, 0x52, 0xe4, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x36, 0xe2, 0xd5, 0x83, 0x9a, 0xa7, 0xe7, 0x9c, 0x9f, 0x92, 0x1a, 0x04, 0x96, 0x12,
	0xb2, 0xe4, 0xe2, 0x4e, 0x86, 0xe8, 0x03, 0xe9, 0x91, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0x12,
	0x87, 0xab, 0xf4, 0x4b, 0x2d, 0x71, 0x46, 0x48, 0x07, 0x21, 0xab, 0x55, 0x72, 0xe0, 0x12, 0x72,
	0xcd, 0x2b, 0x49, 0x2d, 0x42, 0xb2, 0x37, 0xde, 0x59, 0x48, 0x8c, 0x8b, 0x2d, 0x2d, 0x29, 0xa4,
	0xb2, 0x00, 0x62, 0x2b, 0x6b, 0x10, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x92, 0x96, 0xe4, 0x99, 0x22,
	0xc1, 0x04, 0x16, 0x05, 0xb3, 0x95, 0xcc, 0xb1, 0x98, 0x40, 0x8c, 0xab, 0x95, 0x26, 0x30, 0x72,
	0x09, 0x23, 0x69, 0x0a, 0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x89, 0x0f, 0x16, 0x12, 0xe1, 0x62, 0xcd,
	0x2c, 0x2e, 0xcf, 0xcc, 0x03, 0xeb, 0xe5, 0x08, 0x82, 0x70, 0x84, 0x34, 0xb8, 0x58, 0x33, 0x4b,
	0x52, 0x73, 0x8b, 0xa1, 0xbe, 0x13, 0x42, 0xf6, 0x9d, 0x67, 0x49, 0x6a, 0x6e, 0x98, 0x7f, 0x10,
	0x44, 0x01, 0x7a, 0x68, 0x30, 0x83, 0x5d, 0x40, 0x5c, 0x68, 0x38, 0x71, 0x89, 0x04, 0x27, 0xe6,
	0xbb, 0x24, 0xe6, 0xa5, 0x93, 0x1f, 0x1e, 0xf3, 0x18, 0xb1, 0x1a, 0x42, 0x54, 0x44, 0xd2, 0xc5,
	0x93, 0xa8, 0x49, 0xcf, 0xb5, 0x22, 0xb3, 0x24, 0xde, 0x59, 0xc9, 0x0c, 0x53, 0x90, 0x18, 0x17,
	0x3b, 0xc9, 0x72, 0x71, 0x27, 0xe7, 0xe7, 0xc2, 0x64, 0x9c, 0xf8, 0x50, 0xf3, 0x00, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x76, 0x79, 0xe6, 0xaa, 0x14, 0x03, 0x00, 0x00,
}
