// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ChapterMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnterBossChapter_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterBossChapter_C) Reset()         { *m = EnterBossChapter_C{} }
func (m *EnterBossChapter_C) String() string { return proto.CompactTextString(m) }
func (*EnterBossChapter_C) ProtoMessage()    {}
func (*EnterBossChapter_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{0}
}
func (m *EnterBossChapter_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterBossChapter_C.Unmarshal(m, b)
}
func (m *EnterBossChapter_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterBossChapter_C.Marshal(b, m, deterministic)
}
func (dst *EnterBossChapter_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterBossChapter_C.Merge(dst, src)
}
func (m *EnterBossChapter_C) XXX_Size() int {
	return xxx_messageInfo_EnterBossChapter_C.Size(m)
}
func (m *EnterBossChapter_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterBossChapter_C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterBossChapter_C proto.InternalMessageInfo

type EnterBossChapter_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterBossChapter_S) Reset()         { *m = EnterBossChapter_S{} }
func (m *EnterBossChapter_S) String() string { return proto.CompactTextString(m) }
func (*EnterBossChapter_S) ProtoMessage()    {}
func (*EnterBossChapter_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{1}
}
func (m *EnterBossChapter_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterBossChapter_S.Unmarshal(m, b)
}
func (m *EnterBossChapter_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterBossChapter_S.Marshal(b, m, deterministic)
}
func (dst *EnterBossChapter_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterBossChapter_S.Merge(dst, src)
}
func (m *EnterBossChapter_S) XXX_Size() int {
	return xxx_messageInfo_EnterBossChapter_S.Size(m)
}
func (m *EnterBossChapter_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterBossChapter_S.DiscardUnknown(m)
}

var xxx_messageInfo_EnterBossChapter_S proto.InternalMessageInfo

func (m *EnterBossChapter_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type EnterNormalChapter_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterNormalChapter_C) Reset()         { *m = EnterNormalChapter_C{} }
func (m *EnterNormalChapter_C) String() string { return proto.CompactTextString(m) }
func (*EnterNormalChapter_C) ProtoMessage()    {}
func (*EnterNormalChapter_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{2}
}
func (m *EnterNormalChapter_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterNormalChapter_C.Unmarshal(m, b)
}
func (m *EnterNormalChapter_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterNormalChapter_C.Marshal(b, m, deterministic)
}
func (dst *EnterNormalChapter_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterNormalChapter_C.Merge(dst, src)
}
func (m *EnterNormalChapter_C) XXX_Size() int {
	return xxx_messageInfo_EnterNormalChapter_C.Size(m)
}
func (m *EnterNormalChapter_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterNormalChapter_C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterNormalChapter_C proto.InternalMessageInfo

type EnterNormalChapter_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	ChapterId            *int32   `protobuf:"varint,2,opt,name=chapterId" json:"chapterId,omitempty"`
	KillCount            *int32   `protobuf:"varint,3,opt,name=killCount" json:"killCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterNormalChapter_S) Reset()         { *m = EnterNormalChapter_S{} }
func (m *EnterNormalChapter_S) String() string { return proto.CompactTextString(m) }
func (*EnterNormalChapter_S) ProtoMessage()    {}
func (*EnterNormalChapter_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{3}
}
func (m *EnterNormalChapter_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterNormalChapter_S.Unmarshal(m, b)
}
func (m *EnterNormalChapter_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterNormalChapter_S.Marshal(b, m, deterministic)
}
func (dst *EnterNormalChapter_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterNormalChapter_S.Merge(dst, src)
}
func (m *EnterNormalChapter_S) XXX_Size() int {
	return xxx_messageInfo_EnterNormalChapter_S.Size(m)
}
func (m *EnterNormalChapter_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterNormalChapter_S.DiscardUnknown(m)
}

var xxx_messageInfo_EnterNormalChapter_S proto.InternalMessageInfo

func (m *EnterNormalChapter_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EnterNormalChapter_S) GetChapterId() int32 {
	if m != nil && m.ChapterId != nil {
		return *m.ChapterId
	}
	return 0
}

func (m *EnterNormalChapter_S) GetKillCount() int32 {
	if m != nil && m.KillCount != nil {
		return *m.KillCount
	}
	return 0
}

type ChapterResult_S struct {
	Iswin                *bool        `protobuf:"varint,1,opt,name=iswin" json:"iswin,omitempty"`
	Items                []*NetItemVO `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChapterResult_S) Reset()         { *m = ChapterResult_S{} }
func (m *ChapterResult_S) String() string { return proto.CompactTextString(m) }
func (*ChapterResult_S) ProtoMessage()    {}
func (*ChapterResult_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{4}
}
func (m *ChapterResult_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterResult_S.Unmarshal(m, b)
}
func (m *ChapterResult_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterResult_S.Marshal(b, m, deterministic)
}
func (dst *ChapterResult_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterResult_S.Merge(dst, src)
}
func (m *ChapterResult_S) XXX_Size() int {
	return xxx_messageInfo_ChapterResult_S.Size(m)
}
func (m *ChapterResult_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterResult_S.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterResult_S proto.InternalMessageInfo

func (m *ChapterResult_S) GetIswin() bool {
	if m != nil && m.Iswin != nil {
		return *m.Iswin
	}
	return false
}

func (m *ChapterResult_S) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

type ChapterRankData struct {
	Rank                 *int32   `protobuf:"varint,1,opt,name=rank" json:"rank,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Id                   *int32   `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterRankData) Reset()         { *m = ChapterRankData{} }
func (m *ChapterRankData) String() string { return proto.CompactTextString(m) }
func (*ChapterRankData) ProtoMessage()    {}
func (*ChapterRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{5}
}
func (m *ChapterRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterRankData.Unmarshal(m, b)
}
func (m *ChapterRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterRankData.Marshal(b, m, deterministic)
}
func (dst *ChapterRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterRankData.Merge(dst, src)
}
func (m *ChapterRankData) XXX_Size() int {
	return xxx_messageInfo_ChapterRankData.Size(m)
}
func (m *ChapterRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterRankData.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterRankData proto.InternalMessageInfo

func (m *ChapterRankData) GetRank() int32 {
	if m != nil && m.Rank != nil {
		return *m.Rank
	}
	return 0
}

func (m *ChapterRankData) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ChapterRankData) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ChapterRank_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterRank_C) Reset()         { *m = ChapterRank_C{} }
func (m *ChapterRank_C) String() string { return proto.CompactTextString(m) }
func (*ChapterRank_C) ProtoMessage()    {}
func (*ChapterRank_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{6}
}
func (m *ChapterRank_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterRank_C.Unmarshal(m, b)
}
func (m *ChapterRank_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterRank_C.Marshal(b, m, deterministic)
}
func (dst *ChapterRank_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterRank_C.Merge(dst, src)
}
func (m *ChapterRank_C) XXX_Size() int {
	return xxx_messageInfo_ChapterRank_C.Size(m)
}
func (m *ChapterRank_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterRank_C.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterRank_C proto.InternalMessageInfo

type ChapterRank_S struct {
	Ranks                []*ChapterRankData `protobuf:"bytes,1,rep,name=ranks" json:"ranks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChapterRank_S) Reset()         { *m = ChapterRank_S{} }
func (m *ChapterRank_S) String() string { return proto.CompactTextString(m) }
func (*ChapterRank_S) ProtoMessage()    {}
func (*ChapterRank_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{7}
}
func (m *ChapterRank_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterRank_S.Unmarshal(m, b)
}
func (m *ChapterRank_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterRank_S.Marshal(b, m, deterministic)
}
func (dst *ChapterRank_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterRank_S.Merge(dst, src)
}
func (m *ChapterRank_S) XXX_Size() int {
	return xxx_messageInfo_ChapterRank_S.Size(m)
}
func (m *ChapterRank_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterRank_S.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterRank_S proto.InternalMessageInfo

func (m *ChapterRank_S) GetRanks() []*ChapterRankData {
	if m != nil {
		return m.Ranks
	}
	return nil
}

type ChapterKillTimes_S struct {
	Times                *int32   `protobuf:"varint,1,opt,name=times" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChapterKillTimes_S) Reset()         { *m = ChapterKillTimes_S{} }
func (m *ChapterKillTimes_S) String() string { return proto.CompactTextString(m) }
func (*ChapterKillTimes_S) ProtoMessage()    {}
func (*ChapterKillTimes_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_ChapterMsg_136a95e53cb5e4d9, []int{8}
}
func (m *ChapterKillTimes_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChapterKillTimes_S.Unmarshal(m, b)
}
func (m *ChapterKillTimes_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChapterKillTimes_S.Marshal(b, m, deterministic)
}
func (dst *ChapterKillTimes_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChapterKillTimes_S.Merge(dst, src)
}
func (m *ChapterKillTimes_S) XXX_Size() int {
	return xxx_messageInfo_ChapterKillTimes_S.Size(m)
}
func (m *ChapterKillTimes_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChapterKillTimes_S.DiscardUnknown(m)
}

var xxx_messageInfo_ChapterKillTimes_S proto.InternalMessageInfo

func (m *ChapterKillTimes_S) GetTimes() int32 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

func init() {
	proto.RegisterType((*EnterBossChapter_C)(nil), "message.EnterBossChapter_C")
	proto.RegisterType((*EnterBossChapter_S)(nil), "message.EnterBossChapter_S")
	proto.RegisterType((*EnterNormalChapter_C)(nil), "message.EnterNormalChapter_C")
	proto.RegisterType((*EnterNormalChapter_S)(nil), "message.EnterNormalChapter_S")
	proto.RegisterType((*ChapterResult_S)(nil), "message.ChapterResult_S")
	proto.RegisterType((*ChapterRankData)(nil), "message.ChapterRankData")
	proto.RegisterType((*ChapterRank_C)(nil), "message.ChapterRank_C")
	proto.RegisterType((*ChapterRank_S)(nil), "message.ChapterRank_S")
	proto.RegisterType((*ChapterKillTimes_S)(nil), "message.ChapterKillTimes_S")
}

func init() { proto.RegisterFile("ChapterMsg.proto", fileDescriptor_ChapterMsg_136a95e53cb5e4d9) }

var fileDescriptor_ChapterMsg_136a95e53cb5e4d9 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0x49, 0xda, 0xf0, 0x7d, 0x9d, 0x5a, 0x2b, 0x4b, 0x91, 0x28, 0x1e, 0xea, 0x9e, 0x82,
	0x87, 0x1c, 0x7a, 0xf1, 0x28, 0x24, 0x7a, 0x28, 0x62, 0x8b, 0x5b, 0xe9, 0xb5, 0x2c, 0xcd, 0x50,
	0x97, 0x66, 0xb3, 0x25, 0xbb, 0xc1, 0x7f, 0x5f, 0xb2, 0xbb, 0x36, 0x16, 0x7a, 0xf0, 0x36, 0xf3,
	0xde, 0xcc, 0x6f, 0x5e, 0xc2, 0xc2, 0x55, 0xfe, 0xc9, 0x0f, 0x06, 0xeb, 0x37, 0xbd, 0x4b, 0x0f,
	0xb5, 0x32, 0x8a, 0xfc, 0x93, 0xa8, 0x35, 0xdf, 0xe1, 0xed, 0x45, 0xc6, 0x35, 0xae, 0x97, 0x4e,
	0xa6, 0x13, 0x20, 0x2f, 0x95, 0xc1, 0x3a, 0x53, 0x5a, 0xfb, 0x9d, 0x4d, 0x4e, 0x1f, 0xcf, 0xa8,
	0x2b, 0x72, 0x0f, 0xfd, 0xad, 0x2a, 0x30, 0x0e, 0xa6, 0x41, 0x32, 0x9c, 0x8d, 0x52, 0x4f, 0x4c,
	0x73, 0x55, 0x20, 0xb3, 0x16, 0xbd, 0x86, 0x89, 0x5d, 0x5c, 0xa8, 0x5a, 0xf2, 0xb2, 0x03, 0x36,
	0x67, 0xf5, 0xbf, 0x20, 0xc9, 0x1d, 0x0c, 0xb6, 0x6e, 0x7e, 0x5e, 0xc4, 0xe1, 0x34, 0x48, 0x22,
	0xd6, 0x09, 0xad, 0xbb, 0x17, 0x65, 0x99, 0xab, 0xa6, 0x32, 0x71, 0xcf, 0xb9, 0x47, 0x81, 0xbe,
	0xc3, 0xd8, 0xdf, 0x62, 0xa8, 0x9b, 0xd2, 0x6c, 0x56, 0x64, 0x02, 0x91, 0xd0, 0x5f, 0xa2, 0xb2,
	0x27, 0xff, 0x33, 0xd7, 0x90, 0x04, 0x22, 0x61, 0x50, 0xea, 0x38, 0x9c, 0xf6, 0x92, 0xe1, 0x8c,
	0x1c, 0x83, 0x2c, 0xd0, 0xcc, 0x0d, 0xca, 0xf5, 0x92, 0xb9, 0x01, 0x3a, 0xef, 0x90, 0xbc, 0xda,
	0x3f, 0x73, 0xc3, 0x09, 0x81, 0x7e, 0xcd, 0xab, 0xbd, 0x25, 0x46, 0xcc, 0xd6, 0xad, 0x56, 0x71,
	0x89, 0x36, 0xf0, 0x80, 0xd9, 0x9a, 0x5c, 0x42, 0x28, 0x0a, 0x1f, 0x32, 0x14, 0x05, 0x1d, 0xc3,
	0xe8, 0x17, 0x6a, 0x93, 0xd3, 0xa7, 0x53, 0x61, 0x45, 0x52, 0x88, 0x5a, 0x9a, 0x8e, 0x03, 0x1b,
	0x2b, 0xee, 0xfe, 0xcf, 0x69, 0x04, 0xe6, 0xc6, 0xe8, 0x03, 0x10, 0xef, 0xbc, 0x8a, 0xb2, 0xfc,
	0x10, 0x12, 0xb5, 0xfb, 0x64, 0xd3, 0x96, 0x3e, 0xa0, 0x6b, 0xb2, 0x1b, 0x18, 0x6e, 0x95, 0xfc,
	0x21, 0x66, 0xd0, 0xbd, 0x98, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0xaf, 0xc4, 0xae, 0x3e,
	0x02, 0x00, 0x00,
}
