// Code generated by protoc-gen-go. DO NOT EDIT.
// source: EliteZoneMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EliteZoneInfo_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EliteZoneInfo_C) Reset()         { *m = EliteZoneInfo_C{} }
func (m *EliteZoneInfo_C) String() string { return proto.CompactTextString(m) }
func (*EliteZoneInfo_C) ProtoMessage()    {}
func (*EliteZoneInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{0}
}
func (m *EliteZoneInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EliteZoneInfo_C.Unmarshal(m, b)
}
func (m *EliteZoneInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EliteZoneInfo_C.Marshal(b, m, deterministic)
}
func (dst *EliteZoneInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EliteZoneInfo_C.Merge(dst, src)
}
func (m *EliteZoneInfo_C) XXX_Size() int {
	return xxx_messageInfo_EliteZoneInfo_C.Size(m)
}
func (m *EliteZoneInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EliteZoneInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_EliteZoneInfo_C proto.InternalMessageInfo

type EliteZoneInfo_S struct {
	Code                 *Code           `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	MaxTplId             *int32          `protobuf:"varint,2,opt,name=maxTplId" json:"maxTplId,omitempty"`
	TotalTimes           *int32          `protobuf:"varint,3,opt,name=totalTimes" json:"totalTimes,omitempty"`
	EliteInfo            []*NetEliteInfo `protobuf:"bytes,4,rep,name=eliteInfo" json:"eliteInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EliteZoneInfo_S) Reset()         { *m = EliteZoneInfo_S{} }
func (m *EliteZoneInfo_S) String() string { return proto.CompactTextString(m) }
func (*EliteZoneInfo_S) ProtoMessage()    {}
func (*EliteZoneInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{1}
}
func (m *EliteZoneInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EliteZoneInfo_S.Unmarshal(m, b)
}
func (m *EliteZoneInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EliteZoneInfo_S.Marshal(b, m, deterministic)
}
func (dst *EliteZoneInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EliteZoneInfo_S.Merge(dst, src)
}
func (m *EliteZoneInfo_S) XXX_Size() int {
	return xxx_messageInfo_EliteZoneInfo_S.Size(m)
}
func (m *EliteZoneInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EliteZoneInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_EliteZoneInfo_S proto.InternalMessageInfo

func (m *EliteZoneInfo_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *EliteZoneInfo_S) GetMaxTplId() int32 {
	if m != nil && m.MaxTplId != nil {
		return *m.MaxTplId
	}
	return 0
}

func (m *EliteZoneInfo_S) GetTotalTimes() int32 {
	if m != nil && m.TotalTimes != nil {
		return *m.TotalTimes
	}
	return 0
}

func (m *EliteZoneInfo_S) GetEliteInfo() []*NetEliteInfo {
	if m != nil {
		return m.EliteInfo
	}
	return nil
}

type EnterEliteZone_C struct {
	CfgId                *int32   `protobuf:"varint,1,opt,name=cfgId" json:"cfgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterEliteZone_C) Reset()         { *m = EnterEliteZone_C{} }
func (m *EnterEliteZone_C) String() string { return proto.CompactTextString(m) }
func (*EnterEliteZone_C) ProtoMessage()    {}
func (*EnterEliteZone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{2}
}
func (m *EnterEliteZone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterEliteZone_C.Unmarshal(m, b)
}
func (m *EnterEliteZone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterEliteZone_C.Marshal(b, m, deterministic)
}
func (dst *EnterEliteZone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterEliteZone_C.Merge(dst, src)
}
func (m *EnterEliteZone_C) XXX_Size() int {
	return xxx_messageInfo_EnterEliteZone_C.Size(m)
}
func (m *EnterEliteZone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterEliteZone_C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterEliteZone_C proto.InternalMessageInfo

func (m *EnterEliteZone_C) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

type EnterEliteZone_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterEliteZone_S) Reset()         { *m = EnterEliteZone_S{} }
func (m *EnterEliteZone_S) String() string { return proto.CompactTextString(m) }
func (*EnterEliteZone_S) ProtoMessage()    {}
func (*EnterEliteZone_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{3}
}
func (m *EnterEliteZone_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterEliteZone_S.Unmarshal(m, b)
}
func (m *EnterEliteZone_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterEliteZone_S.Marshal(b, m, deterministic)
}
func (dst *EnterEliteZone_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterEliteZone_S.Merge(dst, src)
}
func (m *EnterEliteZone_S) XXX_Size() int {
	return xxx_messageInfo_EnterEliteZone_S.Size(m)
}
func (m *EnterEliteZone_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterEliteZone_S.DiscardUnknown(m)
}

var xxx_messageInfo_EnterEliteZone_S proto.InternalMessageInfo

func (m *EnterEliteZone_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type EliteZoneResult_S struct {
	Iswin                *bool         `protobuf:"varint,1,opt,name=iswin" json:"iswin,omitempty"`
	Items                []*NetItemVO  `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	EliteInfo            *NetEliteInfo `protobuf:"bytes,3,opt,name=eliteInfo" json:"eliteInfo,omitempty"`
	MaxTplId             *int32        `protobuf:"varint,4,opt,name=maxTplId" json:"maxTplId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EliteZoneResult_S) Reset()         { *m = EliteZoneResult_S{} }
func (m *EliteZoneResult_S) String() string { return proto.CompactTextString(m) }
func (*EliteZoneResult_S) ProtoMessage()    {}
func (*EliteZoneResult_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{4}
}
func (m *EliteZoneResult_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EliteZoneResult_S.Unmarshal(m, b)
}
func (m *EliteZoneResult_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EliteZoneResult_S.Marshal(b, m, deterministic)
}
func (dst *EliteZoneResult_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EliteZoneResult_S.Merge(dst, src)
}
func (m *EliteZoneResult_S) XXX_Size() int {
	return xxx_messageInfo_EliteZoneResult_S.Size(m)
}
func (m *EliteZoneResult_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EliteZoneResult_S.DiscardUnknown(m)
}

var xxx_messageInfo_EliteZoneResult_S proto.InternalMessageInfo

func (m *EliteZoneResult_S) GetIswin() bool {
	if m != nil && m.Iswin != nil {
		return *m.Iswin
	}
	return false
}

func (m *EliteZoneResult_S) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *EliteZoneResult_S) GetEliteInfo() *NetEliteInfo {
	if m != nil {
		return m.EliteInfo
	}
	return nil
}

func (m *EliteZoneResult_S) GetMaxTplId() int32 {
	if m != nil && m.MaxTplId != nil {
		return *m.MaxTplId
	}
	return 0
}

type SaoDangEliteZone_C struct {
	CfgId                *int32   `protobuf:"varint,1,opt,name=cfgId" json:"cfgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaoDangEliteZone_C) Reset()         { *m = SaoDangEliteZone_C{} }
func (m *SaoDangEliteZone_C) String() string { return proto.CompactTextString(m) }
func (*SaoDangEliteZone_C) ProtoMessage()    {}
func (*SaoDangEliteZone_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{5}
}
func (m *SaoDangEliteZone_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaoDangEliteZone_C.Unmarshal(m, b)
}
func (m *SaoDangEliteZone_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaoDangEliteZone_C.Marshal(b, m, deterministic)
}
func (dst *SaoDangEliteZone_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaoDangEliteZone_C.Merge(dst, src)
}
func (m *SaoDangEliteZone_C) XXX_Size() int {
	return xxx_messageInfo_SaoDangEliteZone_C.Size(m)
}
func (m *SaoDangEliteZone_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SaoDangEliteZone_C.DiscardUnknown(m)
}

var xxx_messageInfo_SaoDangEliteZone_C proto.InternalMessageInfo

func (m *SaoDangEliteZone_C) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

type SaoDangEliteZone_S struct {
	Code                 *Code         `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	TotalTimes           *int32        `protobuf:"varint,2,opt,name=totalTimes" json:"totalTimes,omitempty"`
	Items                []*NetItemVOs `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	EliteInfo            *NetEliteInfo `protobuf:"bytes,4,opt,name=eliteInfo" json:"eliteInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SaoDangEliteZone_S) Reset()         { *m = SaoDangEliteZone_S{} }
func (m *SaoDangEliteZone_S) String() string { return proto.CompactTextString(m) }
func (*SaoDangEliteZone_S) ProtoMessage()    {}
func (*SaoDangEliteZone_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{6}
}
func (m *SaoDangEliteZone_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaoDangEliteZone_S.Unmarshal(m, b)
}
func (m *SaoDangEliteZone_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaoDangEliteZone_S.Marshal(b, m, deterministic)
}
func (dst *SaoDangEliteZone_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaoDangEliteZone_S.Merge(dst, src)
}
func (m *SaoDangEliteZone_S) XXX_Size() int {
	return xxx_messageInfo_SaoDangEliteZone_S.Size(m)
}
func (m *SaoDangEliteZone_S) XXX_DiscardUnknown() {
	xxx_messageInfo_SaoDangEliteZone_S.DiscardUnknown(m)
}

var xxx_messageInfo_SaoDangEliteZone_S proto.InternalMessageInfo

func (m *SaoDangEliteZone_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *SaoDangEliteZone_S) GetTotalTimes() int32 {
	if m != nil && m.TotalTimes != nil {
		return *m.TotalTimes
	}
	return 0
}

func (m *SaoDangEliteZone_S) GetItems() []*NetItemVOs {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *SaoDangEliteZone_S) GetEliteInfo() *NetEliteInfo {
	if m != nil {
		return m.EliteInfo
	}
	return nil
}

type EliteZoneExit_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EliteZoneExit_C) Reset()         { *m = EliteZoneExit_C{} }
func (m *EliteZoneExit_C) String() string { return proto.CompactTextString(m) }
func (*EliteZoneExit_C) ProtoMessage()    {}
func (*EliteZoneExit_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{7}
}
func (m *EliteZoneExit_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EliteZoneExit_C.Unmarshal(m, b)
}
func (m *EliteZoneExit_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EliteZoneExit_C.Marshal(b, m, deterministic)
}
func (dst *EliteZoneExit_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EliteZoneExit_C.Merge(dst, src)
}
func (m *EliteZoneExit_C) XXX_Size() int {
	return xxx_messageInfo_EliteZoneExit_C.Size(m)
}
func (m *EliteZoneExit_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EliteZoneExit_C.DiscardUnknown(m)
}

var xxx_messageInfo_EliteZoneExit_C proto.InternalMessageInfo

type EliteZoneExit_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EliteZoneExit_S) Reset()         { *m = EliteZoneExit_S{} }
func (m *EliteZoneExit_S) String() string { return proto.CompactTextString(m) }
func (*EliteZoneExit_S) ProtoMessage()    {}
func (*EliteZoneExit_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_EliteZoneMsg_27f4f3559f93c544, []int{8}
}
func (m *EliteZoneExit_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EliteZoneExit_S.Unmarshal(m, b)
}
func (m *EliteZoneExit_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EliteZoneExit_S.Marshal(b, m, deterministic)
}
func (dst *EliteZoneExit_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EliteZoneExit_S.Merge(dst, src)
}
func (m *EliteZoneExit_S) XXX_Size() int {
	return xxx_messageInfo_EliteZoneExit_S.Size(m)
}
func (m *EliteZoneExit_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EliteZoneExit_S.DiscardUnknown(m)
}

var xxx_messageInfo_EliteZoneExit_S proto.InternalMessageInfo

func (m *EliteZoneExit_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func init() {
	proto.RegisterType((*EliteZoneInfo_C)(nil), "message.EliteZoneInfo_C")
	proto.RegisterType((*EliteZoneInfo_S)(nil), "message.EliteZoneInfo_S")
	proto.RegisterType((*EnterEliteZone_C)(nil), "message.EnterEliteZone_C")
	proto.RegisterType((*EnterEliteZone_S)(nil), "message.EnterEliteZone_S")
	proto.RegisterType((*EliteZoneResult_S)(nil), "message.EliteZoneResult_S")
	proto.RegisterType((*SaoDangEliteZone_C)(nil), "message.SaoDangEliteZone_C")
	proto.RegisterType((*SaoDangEliteZone_S)(nil), "message.SaoDangEliteZone_S")
	proto.RegisterType((*EliteZoneExit_C)(nil), "message.EliteZoneExit_C")
	proto.RegisterType((*EliteZoneExit_S)(nil), "message.EliteZoneExit_S")
}

func init() { proto.RegisterFile("EliteZoneMsg.proto", fileDescriptor_EliteZoneMsg_27f4f3559f93c544) }

var fileDescriptor_EliteZoneMsg_27f4f3559f93c544 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x53, 0xda, 0x46, 0x1c, 0x30, 0xca, 0xaa, 0x49, 0x83, 0x89, 0xc1, 0x3d, 0x55, 0x0f,
	0x1c, 0x50, 0x5f, 0x80, 0xda, 0x43, 0x0f, 0x4a, 0xb2, 0x10, 0x0e, 0x5e, 0x9a, 0x86, 0x0e, 0x4d,
	0x93, 0x6e, 0x97, 0xb0, 0x6b, 0xe4, 0x81, 0xf4, 0x19, 0x7c, 0x3d, 0xc3, 0x56, 0x2a, 0x05, 0x12,
	0x7a, 0x9c, 0x99, 0x7f, 0xfa, 0xcf, 0x7c, 0xd3, 0x05, 0xe2, 0x67, 0xa9, 0xc2, 0x77, 0x91, 0xe3,
	0xab, 0x4c, 0xfa, 0x8b, 0xa5, 0x50, 0x82, 0x9c, 0x70, 0x94, 0x32, 0x4a, 0xb0, 0xdb, 0x1e, 0x46,
	0x12, 0xa7, 0xa3, 0x22, 0x4d, 0x3b, 0x70, 0x5e, 0x8a, 0x83, 0x7c, 0x2e, 0x42, 0x8f, 0x7e, 0x1b,
	0xbb, 0xb9, 0x31, 0xb9, 0x03, 0x6b, 0x26, 0x62, 0x74, 0x8c, 0x9e, 0xe1, 0xb6, 0x06, 0x67, 0xfd,
	0xbf, 0x8f, 0xf5, 0x3d, 0x11, 0x23, 0xd3, 0x25, 0xd2, 0x85, 0x26, 0x8f, 0x56, 0x93, 0x45, 0x16,
	0xc4, 0x4e, 0xa3, 0x67, 0xb8, 0x36, 0x2b, 0x63, 0x72, 0x0b, 0xa0, 0x84, 0x8a, 0xb2, 0x49, 0xca,
	0x51, 0x3a, 0xa6, 0xae, 0x6e, 0x65, 0xc8, 0x23, 0x9c, 0xe2, 0xda, 0x71, 0xed, 0xe6, 0x58, 0x3d,
	0xd3, 0x6d, 0x0d, 0xae, 0x4b, 0x8f, 0x37, 0x54, 0xfe, 0xa6, 0xc8, 0xfe, 0x75, 0xd4, 0x85, 0x0b,
	0x3f, 0x57, 0xb8, 0x2c, 0x67, 0x0d, 0x3d, 0x72, 0x05, 0xf6, 0x6c, 0x9e, 0x04, 0xb1, 0x1e, 0xd4,
	0x66, 0x45, 0x40, 0x9f, 0xf7, 0x94, 0x75, 0x36, 0xa2, 0x5f, 0x06, 0x74, 0xca, 0x16, 0x86, 0xf2,
	0x23, 0x53, 0xe1, 0x78, 0x6d, 0x91, 0xca, 0xcf, 0x34, 0xd7, 0x9d, 0x4d, 0x56, 0x04, 0xc4, 0x05,
	0x3b, 0x55, 0xc8, 0xa5, 0xd3, 0xd0, 0xd3, 0x93, 0xed, 0xe9, 0x03, 0x85, 0x7c, 0x3a, 0x62, 0x85,
	0xa0, 0xba, 0xab, 0xa9, 0xdd, 0x8f, 0xee, 0x5a, 0x81, 0x6b, 0x55, 0xe1, 0xd2, 0x07, 0x20, 0xe3,
	0x48, 0xbc, 0x44, 0x79, 0x72, 0x9c, 0xc4, 0x8f, 0x71, 0x40, 0x5c, 0xeb, 0xbc, 0xd5, 0x13, 0x36,
	0xf6, 0x4e, 0x78, 0xbf, 0x01, 0x60, 0x6a, 0x00, 0x97, 0xfb, 0x00, 0xe4, 0x41, 0x02, 0x56, 0x3d,
	0x02, 0x95, 0x1f, 0xd5, 0x5f, 0xa5, 0x2a, 0xf4, 0xe8, 0xd3, 0x6e, 0xaa, 0xce, 0x22, 0xc3, 0x1b,
	0x68, 0xcd, 0x04, 0xdf, 0x54, 0x86, 0xed, 0xed, 0xb7, 0xf2, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x8f,
	0xbb, 0x90, 0x6a, 0x3a, 0x03, 0x00, 0x00,
}
