// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Fight.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HarmType int32

const (
	HarmType_HarmType_Miss           HarmType = 1
	HarmType_HarmType_Attack         HarmType = 2
	HarmType_HarmType_CriticalAttack HarmType = 3
	HarmType_HarmType_Heal           HarmType = 4
	HarmType_HarmType_CriticalHeal   HarmType = 5
	HarmType_HarmType_Suck           HarmType = 6
	HarmType_HarmType_Didang         HarmType = 7
	HarmType_HarmType_Fanji          HarmType = 8
)

var HarmType_name = map[int32]string{
	1: "HarmType_Miss",
	2: "HarmType_Attack",
	3: "HarmType_CriticalAttack",
	4: "HarmType_Heal",
	5: "HarmType_CriticalHeal",
	6: "HarmType_Suck",
	7: "HarmType_Didang",
	8: "HarmType_Fanji",
}
var HarmType_value = map[string]int32{
	"HarmType_Miss":           1,
	"HarmType_Attack":         2,
	"HarmType_CriticalAttack": 3,
	"HarmType_Heal":           4,
	"HarmType_CriticalHeal":   5,
	"HarmType_Suck":           6,
	"HarmType_Didang":         7,
	"HarmType_Fanji":          8,
}

func (x HarmType) Enum() *HarmType {
	p := new(HarmType)
	*p = x
	return p
}
func (x HarmType) String() string {
	return proto.EnumName(HarmType_name, int32(x))
}
func (x *HarmType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(HarmType_value, data, "HarmType")
	if err != nil {
		return err
	}
	*x = HarmType(value)
	return nil
}
func (HarmType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{0}
}

type FightAttackVO struct {
	HarmInfos            []*NetHarmInfo `protobuf:"bytes,1,rep,name=harmInfos" json:"harmInfos,omitempty"`
	SkillId              *int32         `protobuf:"varint,2,opt,name=skillId" json:"skillId,omitempty"`
	AttackId             *int64         `protobuf:"varint,3,opt,name=attackId" json:"attackId,omitempty"`
	MainTarget           *int64         `protobuf:"varint,4,opt,name=mainTarget" json:"mainTarget,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FightAttackVO) Reset()         { *m = FightAttackVO{} }
func (m *FightAttackVO) String() string { return proto.CompactTextString(m) }
func (*FightAttackVO) ProtoMessage()    {}
func (*FightAttackVO) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{0}
}
func (m *FightAttackVO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightAttackVO.Unmarshal(m, b)
}
func (m *FightAttackVO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightAttackVO.Marshal(b, m, deterministic)
}
func (dst *FightAttackVO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightAttackVO.Merge(dst, src)
}
func (m *FightAttackVO) XXX_Size() int {
	return xxx_messageInfo_FightAttackVO.Size(m)
}
func (m *FightAttackVO) XXX_DiscardUnknown() {
	xxx_messageInfo_FightAttackVO.DiscardUnknown(m)
}

var xxx_messageInfo_FightAttackVO proto.InternalMessageInfo

func (m *FightAttackVO) GetHarmInfos() []*NetHarmInfo {
	if m != nil {
		return m.HarmInfos
	}
	return nil
}

func (m *FightAttackVO) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *FightAttackVO) GetAttackId() int64 {
	if m != nil && m.AttackId != nil {
		return *m.AttackId
	}
	return 0
}

func (m *FightAttackVO) GetMainTarget() int64 {
	if m != nil && m.MainTarget != nil {
		return *m.MainTarget
	}
	return 0
}

type FightFire_C struct {
	SkillId              *int32   `protobuf:"varint,1,opt,name=skillId" json:"skillId,omitempty"`
	AttackId             *int64   `protobuf:"varint,2,opt,name=attackId" json:"attackId,omitempty"`
	TargetIds            []int64  `protobuf:"varint,3,rep,name=targetIds" json:"targetIds,omitempty"`
	MainTarget           *int64   `protobuf:"varint,4,opt,name=mainTarget" json:"mainTarget,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightFire_C) Reset()         { *m = FightFire_C{} }
func (m *FightFire_C) String() string { return proto.CompactTextString(m) }
func (*FightFire_C) ProtoMessage()    {}
func (*FightFire_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{1}
}
func (m *FightFire_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightFire_C.Unmarshal(m, b)
}
func (m *FightFire_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightFire_C.Marshal(b, m, deterministic)
}
func (dst *FightFire_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightFire_C.Merge(dst, src)
}
func (m *FightFire_C) XXX_Size() int {
	return xxx_messageInfo_FightFire_C.Size(m)
}
func (m *FightFire_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightFire_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightFire_C proto.InternalMessageInfo

func (m *FightFire_C) GetSkillId() int32 {
	if m != nil && m.SkillId != nil {
		return *m.SkillId
	}
	return 0
}

func (m *FightFire_C) GetAttackId() int64 {
	if m != nil && m.AttackId != nil {
		return *m.AttackId
	}
	return 0
}

func (m *FightFire_C) GetTargetIds() []int64 {
	if m != nil {
		return m.TargetIds
	}
	return nil
}

func (m *FightFire_C) GetMainTarget() int64 {
	if m != nil && m.MainTarget != nil {
		return *m.MainTarget
	}
	return 0
}

type FightFire_S struct {
	Code                 *Code            `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Infos                []*FightAttackVO `protobuf:"bytes,2,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FightFire_S) Reset()         { *m = FightFire_S{} }
func (m *FightFire_S) String() string { return proto.CompactTextString(m) }
func (*FightFire_S) ProtoMessage()    {}
func (*FightFire_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{2}
}
func (m *FightFire_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightFire_S.Unmarshal(m, b)
}
func (m *FightFire_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightFire_S.Marshal(b, m, deterministic)
}
func (dst *FightFire_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightFire_S.Merge(dst, src)
}
func (m *FightFire_S) XXX_Size() int {
	return xxx_messageInfo_FightFire_S.Size(m)
}
func (m *FightFire_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightFire_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightFire_S proto.InternalMessageInfo

func (m *FightFire_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *FightFire_S) GetInfos() []*FightAttackVO {
	if m != nil {
		return m.Infos
	}
	return nil
}

type FightCount_S struct {
	Count                *int32   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightCount_S) Reset()         { *m = FightCount_S{} }
func (m *FightCount_S) String() string { return proto.CompactTextString(m) }
func (*FightCount_S) ProtoMessage()    {}
func (*FightCount_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{3}
}
func (m *FightCount_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightCount_S.Unmarshal(m, b)
}
func (m *FightCount_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightCount_S.Marshal(b, m, deterministic)
}
func (dst *FightCount_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightCount_S.Merge(dst, src)
}
func (m *FightCount_S) XXX_Size() int {
	return xxx_messageInfo_FightCount_S.Size(m)
}
func (m *FightCount_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightCount_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightCount_S proto.InternalMessageInfo

func (m *FightCount_S) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

type FightReady_S struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Round                *int32   `protobuf:"varint,2,opt,name=round" json:"round,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightReady_S) Reset()         { *m = FightReady_S{} }
func (m *FightReady_S) String() string { return proto.CompactTextString(m) }
func (*FightReady_S) ProtoMessage()    {}
func (*FightReady_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{4}
}
func (m *FightReady_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightReady_S.Unmarshal(m, b)
}
func (m *FightReady_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightReady_S.Marshal(b, m, deterministic)
}
func (dst *FightReady_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightReady_S.Merge(dst, src)
}
func (m *FightReady_S) XXX_Size() int {
	return xxx_messageInfo_FightReady_S.Size(m)
}
func (m *FightReady_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightReady_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightReady_S proto.InternalMessageInfo

func (m *FightReady_S) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *FightReady_S) GetRound() int32 {
	if m != nil && m.Round != nil {
		return *m.Round
	}
	return 0
}

type FightOver_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightOver_C) Reset()         { *m = FightOver_C{} }
func (m *FightOver_C) String() string { return proto.CompactTextString(m) }
func (*FightOver_C) ProtoMessage()    {}
func (*FightOver_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{5}
}
func (m *FightOver_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightOver_C.Unmarshal(m, b)
}
func (m *FightOver_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightOver_C.Marshal(b, m, deterministic)
}
func (dst *FightOver_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightOver_C.Merge(dst, src)
}
func (m *FightOver_C) XXX_Size() int {
	return xxx_messageInfo_FightOver_C.Size(m)
}
func (m *FightOver_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightOver_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightOver_C proto.InternalMessageInfo

func (m *FightOver_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

type FightSceneReady_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightSceneReady_C) Reset()         { *m = FightSceneReady_C{} }
func (m *FightSceneReady_C) String() string { return proto.CompactTextString(m) }
func (*FightSceneReady_C) ProtoMessage()    {}
func (*FightSceneReady_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{6}
}
func (m *FightSceneReady_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightSceneReady_C.Unmarshal(m, b)
}
func (m *FightSceneReady_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightSceneReady_C.Marshal(b, m, deterministic)
}
func (dst *FightSceneReady_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightSceneReady_C.Merge(dst, src)
}
func (m *FightSceneReady_C) XXX_Size() int {
	return xxx_messageInfo_FightSceneReady_C.Size(m)
}
func (m *FightSceneReady_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightSceneReady_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightSceneReady_C proto.InternalMessageInfo

type FightEnd_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightEnd_C) Reset()         { *m = FightEnd_C{} }
func (m *FightEnd_C) String() string { return proto.CompactTextString(m) }
func (*FightEnd_C) ProtoMessage()    {}
func (*FightEnd_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{7}
}
func (m *FightEnd_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightEnd_C.Unmarshal(m, b)
}
func (m *FightEnd_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightEnd_C.Marshal(b, m, deterministic)
}
func (dst *FightEnd_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightEnd_C.Merge(dst, src)
}
func (m *FightEnd_C) XXX_Size() int {
	return xxx_messageInfo_FightEnd_C.Size(m)
}
func (m *FightEnd_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightEnd_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightEnd_C proto.InternalMessageInfo

type FightExit_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightExit_C) Reset()         { *m = FightExit_C{} }
func (m *FightExit_C) String() string { return proto.CompactTextString(m) }
func (*FightExit_C) ProtoMessage()    {}
func (*FightExit_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{8}
}
func (m *FightExit_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightExit_C.Unmarshal(m, b)
}
func (m *FightExit_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightExit_C.Marshal(b, m, deterministic)
}
func (dst *FightExit_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightExit_C.Merge(dst, src)
}
func (m *FightExit_C) XXX_Size() int {
	return xxx_messageInfo_FightExit_C.Size(m)
}
func (m *FightExit_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightExit_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightExit_C proto.InternalMessageInfo

type FightExit_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightExit_S) Reset()         { *m = FightExit_S{} }
func (m *FightExit_S) String() string { return proto.CompactTextString(m) }
func (*FightExit_S) ProtoMessage()    {}
func (*FightExit_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{9}
}
func (m *FightExit_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightExit_S.Unmarshal(m, b)
}
func (m *FightExit_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightExit_S.Marshal(b, m, deterministic)
}
func (dst *FightExit_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightExit_S.Merge(dst, src)
}
func (m *FightExit_S) XXX_Size() int {
	return xxx_messageInfo_FightExit_S.Size(m)
}
func (m *FightExit_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightExit_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightExit_S proto.InternalMessageInfo

func (m *FightExit_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type FightRoleExp struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Exp                  *int32   `protobuf:"varint,2,opt,name=exp" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightRoleExp) Reset()         { *m = FightRoleExp{} }
func (m *FightRoleExp) String() string { return proto.CompactTextString(m) }
func (*FightRoleExp) ProtoMessage()    {}
func (*FightRoleExp) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{10}
}
func (m *FightRoleExp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightRoleExp.Unmarshal(m, b)
}
func (m *FightRoleExp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightRoleExp.Marshal(b, m, deterministic)
}
func (dst *FightRoleExp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightRoleExp.Merge(dst, src)
}
func (m *FightRoleExp) XXX_Size() int {
	return xxx_messageInfo_FightRoleExp.Size(m)
}
func (m *FightRoleExp) XXX_DiscardUnknown() {
	xxx_messageInfo_FightRoleExp.DiscardUnknown(m)
}

var xxx_messageInfo_FightRoleExp proto.InternalMessageInfo

func (m *FightRoleExp) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *FightRoleExp) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

type FightResult_S struct {
	Iswin                *bool           `protobuf:"varint,1,opt,name=iswin" json:"iswin,omitempty"`
	Items                []*NetItemVO    `protobuf:"bytes,2,rep,name=items" json:"items,omitempty"`
	Roleexp              []*FightRoleExp `protobuf:"bytes,3,rep,name=roleexp" json:"roleexp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FightResult_S) Reset()         { *m = FightResult_S{} }
func (m *FightResult_S) String() string { return proto.CompactTextString(m) }
func (*FightResult_S) ProtoMessage()    {}
func (*FightResult_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{11}
}
func (m *FightResult_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightResult_S.Unmarshal(m, b)
}
func (m *FightResult_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightResult_S.Marshal(b, m, deterministic)
}
func (dst *FightResult_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightResult_S.Merge(dst, src)
}
func (m *FightResult_S) XXX_Size() int {
	return xxx_messageInfo_FightResult_S.Size(m)
}
func (m *FightResult_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightResult_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightResult_S proto.InternalMessageInfo

func (m *FightResult_S) GetIswin() bool {
	if m != nil && m.Iswin != nil {
		return *m.Iswin
	}
	return false
}

func (m *FightResult_S) GetItems() []*NetItemVO {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *FightResult_S) GetRoleexp() []*FightRoleExp {
	if m != nil {
		return m.Roleexp
	}
	return nil
}

type FightNuQiChange_S struct {
	Nuqi                 *int32   `protobuf:"varint,1,opt,name=nuqi" json:"nuqi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightNuQiChange_S) Reset()         { *m = FightNuQiChange_S{} }
func (m *FightNuQiChange_S) String() string { return proto.CompactTextString(m) }
func (*FightNuQiChange_S) ProtoMessage()    {}
func (*FightNuQiChange_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{12}
}
func (m *FightNuQiChange_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightNuQiChange_S.Unmarshal(m, b)
}
func (m *FightNuQiChange_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightNuQiChange_S.Marshal(b, m, deterministic)
}
func (dst *FightNuQiChange_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightNuQiChange_S.Merge(dst, src)
}
func (m *FightNuQiChange_S) XXX_Size() int {
	return xxx_messageInfo_FightNuQiChange_S.Size(m)
}
func (m *FightNuQiChange_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FightNuQiChange_S.DiscardUnknown(m)
}

var xxx_messageInfo_FightNuQiChange_S proto.InternalMessageInfo

func (m *FightNuQiChange_S) GetNuqi() int32 {
	if m != nil && m.Nuqi != nil {
		return *m.Nuqi
	}
	return 0
}

type FightCountAniComplete_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FightCountAniComplete_C) Reset()         { *m = FightCountAniComplete_C{} }
func (m *FightCountAniComplete_C) String() string { return proto.CompactTextString(m) }
func (*FightCountAniComplete_C) ProtoMessage()    {}
func (*FightCountAniComplete_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Fight_6380bd6bc39e5be0, []int{13}
}
func (m *FightCountAniComplete_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FightCountAniComplete_C.Unmarshal(m, b)
}
func (m *FightCountAniComplete_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FightCountAniComplete_C.Marshal(b, m, deterministic)
}
func (dst *FightCountAniComplete_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FightCountAniComplete_C.Merge(dst, src)
}
func (m *FightCountAniComplete_C) XXX_Size() int {
	return xxx_messageInfo_FightCountAniComplete_C.Size(m)
}
func (m *FightCountAniComplete_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FightCountAniComplete_C.DiscardUnknown(m)
}

var xxx_messageInfo_FightCountAniComplete_C proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FightAttackVO)(nil), "message.FightAttackVO")
	proto.RegisterType((*FightFire_C)(nil), "message.FightFire_C")
	proto.RegisterType((*FightFire_S)(nil), "message.FightFire_S")
	proto.RegisterType((*FightCount_S)(nil), "message.FightCount_S")
	proto.RegisterType((*FightReady_S)(nil), "message.FightReady_S")
	proto.RegisterType((*FightOver_C)(nil), "message.FightOver_C")
	proto.RegisterType((*FightSceneReady_C)(nil), "message.FightSceneReady_C")
	proto.RegisterType((*FightEnd_C)(nil), "message.FightEnd_C")
	proto.RegisterType((*FightExit_C)(nil), "message.FightExit_C")
	proto.RegisterType((*FightExit_S)(nil), "message.FightExit_S")
	proto.RegisterType((*FightRoleExp)(nil), "message.FightRoleExp")
	proto.RegisterType((*FightResult_S)(nil), "message.FightResult_S")
	proto.RegisterType((*FightNuQiChange_S)(nil), "message.FightNuQiChange_S")
	proto.RegisterType((*FightCountAniComplete_C)(nil), "message.FightCountAniComplete_C")
	proto.RegisterEnum("message.HarmType", HarmType_name, HarmType_value)
}

func init() { proto.RegisterFile("Fight.proto", fileDescriptor_Fight_6380bd6bc39e5be0) }

var fileDescriptor_Fight_6380bd6bc39e5be0 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0x98, 0xa4, 0x93, 0x06, 0xdc, 0x6d, 0x4b, 0xdd, 0x82, 0x50, 0xba, 0x42, 0x22,
	0x42, 0xa8, 0xa0, 0x8a, 0x03, 0xd7, 0xd6, 0x34, 0x6a, 0x0e, 0x34, 0xc2, 0xa9, 0x7a, 0xc4, 0x5a,
	0xd9, 0x83, 0xb3, 0xc4, 0x5e, 0x07, 0x7b, 0x0d, 0xe9, 0x0d, 0x1e, 0x83, 0x47, 0xe1, 0xed, 0x90,
	0xd7, 0x6b, 0x27, 0x81, 0x22, 0xb8, 0xcd, 0x7c, 0xf3, 0xcd, 0xdf, 0x37, 0xbb, 0xd0, 0x1b, 0xf1,
	0x68, 0x26, 0x4f, 0x16, 0x59, 0x2a, 0x53, 0xd2, 0x49, 0x30, 0xcf, 0x59, 0x84, 0x47, 0xdb, 0xe7,
	0x2c, 0xc7, 0x9b, 0x49, 0x05, 0xd3, 0x1f, 0x06, 0xf4, 0x15, 0xed, 0x4c, 0x4a, 0x16, 0xcc, 0x6f,
	0x26, 0xe4, 0x14, 0xb6, 0x66, 0x2c, 0x4b, 0xc6, 0xe2, 0x63, 0x9a, 0x3b, 0xc6, 0xc0, 0x1c, 0xf6,
	0x4e, 0xf7, 0x4e, 0x74, 0xf2, 0xc9, 0x15, 0xca, 0x4b, 0x1d, 0xf4, 0x56, 0x34, 0xe2, 0x40, 0x27,
	0x9f, 0xf3, 0x38, 0x1e, 0x87, 0x4e, 0x6b, 0x60, 0x0c, 0x2d, 0xaf, 0x76, 0xc9, 0x11, 0x74, 0x99,
	0xaa, 0x3c, 0x0e, 0x1d, 0x73, 0x60, 0x0c, 0x4d, 0xaf, 0xf1, 0xc9, 0x13, 0x80, 0x84, 0x71, 0x71,
	0xcd, 0xb2, 0x08, 0xa5, 0xd3, 0x56, 0xd1, 0x35, 0x84, 0x7e, 0x37, 0xf4, 0x0a, 0x23, 0x9e, 0xa1,
	0xef, 0xae, 0x77, 0x31, 0xfe, 0xde, 0xa5, 0xf5, 0x5b, 0x97, 0xc7, 0xb0, 0x25, 0x55, 0xbd, 0x71,
	0x98, 0x3b, 0xe6, 0xc0, 0x1c, 0x9a, 0xde, 0x0a, 0xf8, 0xe7, 0x0c, 0x1f, 0xd6, 0x47, 0x98, 0x92,
	0x63, 0x68, 0x07, 0x69, 0x88, 0xaa, 0x7f, 0xef, 0xb4, 0xdf, 0xe8, 0xe2, 0xa6, 0x21, 0x7a, 0x2a,
	0x44, 0x5e, 0x80, 0xc5, 0x95, 0x76, 0x2d, 0xa5, 0xdd, 0xc3, 0x86, 0xb3, 0x21, 0xb3, 0x57, 0x91,
	0xe8, 0x53, 0xd8, 0x56, 0xb8, 0x9b, 0x16, 0x42, 0xfa, 0x53, 0xb2, 0x07, 0x56, 0x50, 0x9a, 0x7a,
	0xc3, 0xca, 0xa1, 0x6f, 0x34, 0xcb, 0x43, 0x16, 0xde, 0xfa, 0x53, 0x42, 0xa0, 0x1d, 0x15, 0xbc,
	0x92, 0xc1, 0xf4, 0x94, 0x5d, 0x66, 0x66, 0x69, 0x21, 0xea, 0x0b, 0x54, 0x0e, 0x3d, 0xd6, 0xf3,
	0x4f, 0xbe, 0x60, 0xe6, 0xbb, 0x77, 0x25, 0xd2, 0x5d, 0xd8, 0x51, 0x94, 0x69, 0x80, 0x02, 0xab,
	0x0e, 0x2e, 0xdd, 0x06, 0x50, 0xe0, 0x85, 0x08, 0x7d, 0x97, 0xf6, 0x75, 0x95, 0x8b, 0x25, 0x97,
	0xbe, 0x4b, 0x5f, 0xad, 0xbb, 0xff, 0x23, 0x0a, 0x7d, 0x5d, 0x2f, 0x90, 0xc6, 0x78, 0xb1, 0x5c,
	0xdc, 0xb9, 0x80, 0x0d, 0x26, 0x2e, 0x17, 0x7a, 0xfc, 0xd2, 0xa4, 0xdf, 0xea, 0xc7, 0xe9, 0x61,
	0x5e, 0xc4, 0x5a, 0x1e, 0x9e, 0x7f, 0xe5, 0x42, 0x25, 0x76, 0xbd, 0xca, 0x21, 0x43, 0xb0, 0xb8,
	0xc4, 0xa4, 0x96, 0x9c, 0xac, 0x3f, 0xd7, 0xb1, 0xc4, 0x44, 0xc9, 0x5d, 0x12, 0xc8, 0x4b, 0xe8,
	0x64, 0x69, 0x8c, 0x65, 0x1f, 0x53, 0x71, 0xf7, 0x37, 0xcf, 0xa3, 0xe7, 0xf3, 0x6a, 0x16, 0x7d,
	0xa6, 0xc5, 0xb9, 0x2a, 0xde, 0x73, 0x77, 0xc6, 0x44, 0x84, 0x95, 0xfc, 0xa2, 0xf8, 0xcc, 0xf5,
	0x8d, 0x94, 0x4d, 0x0f, 0xe1, 0x60, 0x75, 0xc8, 0x33, 0xc1, 0xdd, 0x34, 0x59, 0xc4, 0x28, 0xd1,
	0x77, 0x9f, 0xff, 0x34, 0xa0, 0x5b, 0xfe, 0x9a, 0xeb, 0xdb, 0x05, 0x92, 0x1d, 0xe8, 0xd7, 0xb6,
	0xff, 0x8e, 0xe7, 0xb9, 0x6d, 0x90, 0x5d, 0x78, 0xd0, 0x40, 0xd5, 0xfb, 0xb0, 0x5b, 0xe4, 0x11,
	0x1c, 0x34, 0xa0, 0x9b, 0x71, 0xc9, 0x03, 0x16, 0xeb, 0xa0, 0xb9, 0x51, 0xe4, 0x12, 0x59, 0x6c,
	0xb7, 0xc9, 0x21, 0xec, 0xff, 0xc1, 0x57, 0x21, 0x6b, 0x83, 0x3d, 0x2d, 0x82, 0xb9, 0x7d, 0x6f,
	0xa3, 0xe5, 0x5b, 0x1e, 0x32, 0x11, 0xd9, 0x1d, 0x42, 0xe0, 0x7e, 0x03, 0x8e, 0x98, 0xf8, 0xc4,
	0xed, 0xee, 0xf9, 0x1e, 0xf4, 0x82, 0x34, 0xa9, 0x45, 0x3a, 0xb7, 0xd4, 0x8e, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xdf, 0xe2, 0xd1, 0xff, 0x5a, 0x04, 0x00, 0x00,
}
