// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FuBen.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FubenInfo_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FubenInfo_C) Reset()         { *m = FubenInfo_C{} }
func (m *FubenInfo_C) String() string { return proto.CompactTextString(m) }
func (*FubenInfo_C) ProtoMessage()    {}
func (*FubenInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_FuBen_1921210d7183b709, []int{0}
}
func (m *FubenInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FubenInfo_C.Unmarshal(m, b)
}
func (m *FubenInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FubenInfo_C.Marshal(b, m, deterministic)
}
func (dst *FubenInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FubenInfo_C.Merge(dst, src)
}
func (m *FubenInfo_C) XXX_Size() int {
	return xxx_messageInfo_FubenInfo_C.Size(m)
}
func (m *FubenInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FubenInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_FubenInfo_C proto.InternalMessageInfo

type FubenInfo_S struct {
	Infos                []*NetFubenInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FubenInfo_S) Reset()         { *m = FubenInfo_S{} }
func (m *FubenInfo_S) String() string { return proto.CompactTextString(m) }
func (*FubenInfo_S) ProtoMessage()    {}
func (*FubenInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_FuBen_1921210d7183b709, []int{1}
}
func (m *FubenInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FubenInfo_S.Unmarshal(m, b)
}
func (m *FubenInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FubenInfo_S.Marshal(b, m, deterministic)
}
func (dst *FubenInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FubenInfo_S.Merge(dst, src)
}
func (m *FubenInfo_S) XXX_Size() int {
	return xxx_messageInfo_FubenInfo_S.Size(m)
}
func (m *FubenInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FubenInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_FubenInfo_S proto.InternalMessageInfo

func (m *FubenInfo_S) GetInfos() []*NetFubenInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type FubenEnter_C struct {
	CfgId                *int32   `protobuf:"varint,1,opt,name=cfgId" json:"cfgId,omitempty"`
	Hard                 *int32   `protobuf:"varint,2,opt,name=hard" json:"hard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FubenEnter_C) Reset()         { *m = FubenEnter_C{} }
func (m *FubenEnter_C) String() string { return proto.CompactTextString(m) }
func (*FubenEnter_C) ProtoMessage()    {}
func (*FubenEnter_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_FuBen_1921210d7183b709, []int{2}
}
func (m *FubenEnter_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FubenEnter_C.Unmarshal(m, b)
}
func (m *FubenEnter_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FubenEnter_C.Marshal(b, m, deterministic)
}
func (dst *FubenEnter_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FubenEnter_C.Merge(dst, src)
}
func (m *FubenEnter_C) XXX_Size() int {
	return xxx_messageInfo_FubenEnter_C.Size(m)
}
func (m *FubenEnter_C) XXX_DiscardUnknown() {
	xxx_messageInfo_FubenEnter_C.DiscardUnknown(m)
}

var xxx_messageInfo_FubenEnter_C proto.InternalMessageInfo

func (m *FubenEnter_C) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

func (m *FubenEnter_C) GetHard() int32 {
	if m != nil && m.Hard != nil {
		return *m.Hard
	}
	return 0
}

type FubenEnter_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	CfgId                *int32   `protobuf:"varint,2,opt,name=cfgId" json:"cfgId,omitempty"`
	Hard                 *int32   `protobuf:"varint,3,opt,name=hard" json:"hard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FubenEnter_S) Reset()         { *m = FubenEnter_S{} }
func (m *FubenEnter_S) String() string { return proto.CompactTextString(m) }
func (*FubenEnter_S) ProtoMessage()    {}
func (*FubenEnter_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_FuBen_1921210d7183b709, []int{3}
}
func (m *FubenEnter_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FubenEnter_S.Unmarshal(m, b)
}
func (m *FubenEnter_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FubenEnter_S.Marshal(b, m, deterministic)
}
func (dst *FubenEnter_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FubenEnter_S.Merge(dst, src)
}
func (m *FubenEnter_S) XXX_Size() int {
	return xxx_messageInfo_FubenEnter_S.Size(m)
}
func (m *FubenEnter_S) XXX_DiscardUnknown() {
	xxx_messageInfo_FubenEnter_S.DiscardUnknown(m)
}

var xxx_messageInfo_FubenEnter_S proto.InternalMessageInfo

func (m *FubenEnter_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *FubenEnter_S) GetCfgId() int32 {
	if m != nil && m.CfgId != nil {
		return *m.CfgId
	}
	return 0
}

func (m *FubenEnter_S) GetHard() int32 {
	if m != nil && m.Hard != nil {
		return *m.Hard
	}
	return 0
}

func init() {
	proto.RegisterType((*FubenInfo_C)(nil), "message.FubenInfo_C")
	proto.RegisterType((*FubenInfo_S)(nil), "message.FubenInfo_S")
	proto.RegisterType((*FubenEnter_C)(nil), "message.FubenEnter_C")
	proto.RegisterType((*FubenEnter_S)(nil), "message.FubenEnter_S")
}

func init() { proto.RegisterFile("FuBen.proto", fileDescriptor_FuBen_1921210d7183b709) }

var fileDescriptor_FuBen_1921210d7183b709 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x76, 0x2b, 0x75, 0x4a,
	0xcd, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87, 0x08, 0x2b, 0xf1, 0x82, 0x54, 0x25, 0xa5,
	0xe6, 0x79, 0xe6, 0xa5, 0xe5, 0xc7, 0x3b, 0x2b, 0x59, 0x21, 0x73, 0x83, 0x85, 0xb4, 0xb9, 0x58,
	0x33, 0xf3, 0xd2, 0xf2, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0xa0, 0x86,
	0xe8, 0xf9, 0xa5, 0x96, 0xc0, 0xd5, 0x05, 0x41, 0xd4, 0x28, 0x59, 0x70, 0xf1, 0x80, 0xc5, 0x5c,
	0xf3, 0x4a, 0x52, 0x8b, 0xe2, 0x9d, 0x85, 0x44, 0xb8, 0x58, 0x93, 0xd3, 0xd2, 0x3d, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x8c, 0xc4, 0xa2, 0x14,
	0x09, 0x26, 0xb0, 0x20, 0x98, 0xad, 0x14, 0x8d, 0xa2, 0x33, 0x58, 0x48, 0x91, 0x8b, 0x25, 0x39,
	0x3f, 0x25, 0x15, 0xac, 0x91, 0xdb, 0x88, 0x17, 0x6e, 0xab, 0x73, 0x7e, 0x4a, 0x6a, 0x10, 0x58,
	0x0a, 0x61, 0x38, 0x13, 0x36, 0xc3, 0x99, 0x11, 0x86, 0x3b, 0x89, 0x70, 0x71, 0x27, 0xe7, 0xe7,
	0xc2, 0xcc, 0x70, 0x62, 0x05, 0x07, 0x0a, 0x20, 0x00, 0x00, 0xff, 0xff, 0x87, 0xf5, 0x07, 0x5e,
	0x1c, 0x01, 0x00, 0x00,
}
