// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Login.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Login_C struct {
	AccountId            *string  `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	ServerId             *string  `protobuf:"bytes,2,opt,name=serverId" json:"serverId,omitempty"`
	Encrypt              *string  `protobuf:"bytes,3,opt,name=encrypt" json:"encrypt,omitempty"`
	IsChenMi             *bool    `protobuf:"varint,4,opt,name=isChenMi" json:"isChenMi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login_C) Reset()         { *m = Login_C{} }
func (m *Login_C) String() string { return proto.CompactTextString(m) }
func (*Login_C) ProtoMessage()    {}
func (*Login_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{0}
}
func (m *Login_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_C.Unmarshal(m, b)
}
func (m *Login_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_C.Marshal(b, m, deterministic)
}
func (dst *Login_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_C.Merge(dst, src)
}
func (m *Login_C) XXX_Size() int {
	return xxx_messageInfo_Login_C.Size(m)
}
func (m *Login_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_C.DiscardUnknown(m)
}

var xxx_messageInfo_Login_C proto.InternalMessageInfo

func (m *Login_C) GetAccountId() string {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return ""
}

func (m *Login_C) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *Login_C) GetEncrypt() string {
	if m != nil && m.Encrypt != nil {
		return *m.Encrypt
	}
	return ""
}

func (m *Login_C) GetIsChenMi() bool {
	if m != nil && m.IsChenMi != nil {
		return *m.IsChenMi
	}
	return false
}

type Login_S struct {
	Code                 *Code        `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	User                 *NetUserInfo `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	ServerTime           *int64       `protobuf:"varint,3,opt,name=serverTime" json:"serverTime,omitempty"`
	NowTime              *int64       `protobuf:"varint,4,opt,name=nowTime" json:"nowTime,omitempty"`
	MergeServerTime      *int64       `protobuf:"varint,5,opt,name=mergeServerTime" json:"mergeServerTime,omitempty"`
	ZoneOffMinute        *int32       `protobuf:"varint,6,opt,name=zoneOffMinute" json:"zoneOffMinute,omitempty"`
	IsNeedCreate         *bool        `protobuf:"varint,7,opt,name=isNeedCreate" json:"isNeedCreate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Login_S) Reset()         { *m = Login_S{} }
func (m *Login_S) String() string { return proto.CompactTextString(m) }
func (*Login_S) ProtoMessage()    {}
func (*Login_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{1}
}
func (m *Login_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login_S.Unmarshal(m, b)
}
func (m *Login_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login_S.Marshal(b, m, deterministic)
}
func (dst *Login_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login_S.Merge(dst, src)
}
func (m *Login_S) XXX_Size() int {
	return xxx_messageInfo_Login_S.Size(m)
}
func (m *Login_S) XXX_DiscardUnknown() {
	xxx_messageInfo_Login_S.DiscardUnknown(m)
}

var xxx_messageInfo_Login_S proto.InternalMessageInfo

func (m *Login_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Login_S) GetUser() *NetUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Login_S) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *Login_S) GetNowTime() int64 {
	if m != nil && m.NowTime != nil {
		return *m.NowTime
	}
	return 0
}

func (m *Login_S) GetMergeServerTime() int64 {
	if m != nil && m.MergeServerTime != nil {
		return *m.MergeServerTime
	}
	return 0
}

func (m *Login_S) GetZoneOffMinute() int32 {
	if m != nil && m.ZoneOffMinute != nil {
		return *m.ZoneOffMinute
	}
	return 0
}

func (m *Login_S) GetIsNeedCreate() bool {
	if m != nil && m.IsNeedCreate != nil {
		return *m.IsNeedCreate
	}
	return false
}

type Create_C struct {
	UserId               *string  `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	ServerId             *string  `protobuf:"bytes,2,opt,name=serverId" json:"serverId,omitempty"`
	UserName             *string  `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	ConfigId             *int32   `protobuf:"varint,4,opt,name=configId" json:"configId,omitempty"`
	IsAutoCreate         *bool    `protobuf:"varint,5,opt,name=isAutoCreate" json:"isAutoCreate,omitempty"`
	Jiahui               *int32   `protobuf:"varint,6,opt,name=jiahui" json:"jiahui,omitempty"`
	Sex                  *int32   `protobuf:"varint,7,opt,name=sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Create_C) Reset()         { *m = Create_C{} }
func (m *Create_C) String() string { return proto.CompactTextString(m) }
func (*Create_C) ProtoMessage()    {}
func (*Create_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{2}
}
func (m *Create_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create_C.Unmarshal(m, b)
}
func (m *Create_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create_C.Marshal(b, m, deterministic)
}
func (dst *Create_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create_C.Merge(dst, src)
}
func (m *Create_C) XXX_Size() int {
	return xxx_messageInfo_Create_C.Size(m)
}
func (m *Create_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Create_C.DiscardUnknown(m)
}

var xxx_messageInfo_Create_C proto.InternalMessageInfo

func (m *Create_C) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *Create_C) GetServerId() string {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return ""
}

func (m *Create_C) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *Create_C) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

func (m *Create_C) GetIsAutoCreate() bool {
	if m != nil && m.IsAutoCreate != nil {
		return *m.IsAutoCreate
	}
	return false
}

func (m *Create_C) GetJiahui() int32 {
	if m != nil && m.Jiahui != nil {
		return *m.Jiahui
	}
	return 0
}

func (m *Create_C) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type Create_S struct {
	Code                 *Code        `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Role                 *NetUserInfo `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Create_S) Reset()         { *m = Create_S{} }
func (m *Create_S) String() string { return proto.CompactTextString(m) }
func (*Create_S) ProtoMessage()    {}
func (*Create_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{3}
}
func (m *Create_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Create_S.Unmarshal(m, b)
}
func (m *Create_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Create_S.Marshal(b, m, deterministic)
}
func (dst *Create_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Create_S.Merge(dst, src)
}
func (m *Create_S) XXX_Size() int {
	return xxx_messageInfo_Create_S.Size(m)
}
func (m *Create_S) XXX_DiscardUnknown() {
	xxx_messageInfo_Create_S.DiscardUnknown(m)
}

var xxx_messageInfo_Create_S proto.InternalMessageInfo

func (m *Create_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Create_S) GetRole() *NetUserInfo {
	if m != nil {
		return m.Role
	}
	return nil
}

type EnterGame_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGame_C) Reset()         { *m = EnterGame_C{} }
func (m *EnterGame_C) String() string { return proto.CompactTextString(m) }
func (*EnterGame_C) ProtoMessage()    {}
func (*EnterGame_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{4}
}
func (m *EnterGame_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGame_C.Unmarshal(m, b)
}
func (m *EnterGame_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGame_C.Marshal(b, m, deterministic)
}
func (dst *EnterGame_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGame_C.Merge(dst, src)
}
func (m *EnterGame_C) XXX_Size() int {
	return xxx_messageInfo_EnterGame_C.Size(m)
}
func (m *EnterGame_C) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGame_C.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGame_C proto.InternalMessageInfo

type EnterGame_S struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGame_S) Reset()         { *m = EnterGame_S{} }
func (m *EnterGame_S) String() string { return proto.CompactTextString(m) }
func (*EnterGame_S) ProtoMessage()    {}
func (*EnterGame_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{5}
}
func (m *EnterGame_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGame_S.Unmarshal(m, b)
}
func (m *EnterGame_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGame_S.Marshal(b, m, deterministic)
}
func (dst *EnterGame_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGame_S.Merge(dst, src)
}
func (m *EnterGame_S) XXX_Size() int {
	return xxx_messageInfo_EnterGame_S.Size(m)
}
func (m *EnterGame_S) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGame_S.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGame_S proto.InternalMessageInfo

type ZlibData struct {
	PbData               []*NetPBData `protobuf:"bytes,1,rep,name=pbData" json:"pbData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ZlibData) Reset()         { *m = ZlibData{} }
func (m *ZlibData) String() string { return proto.CompactTextString(m) }
func (*ZlibData) ProtoMessage()    {}
func (*ZlibData) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{6}
}
func (m *ZlibData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZlibData.Unmarshal(m, b)
}
func (m *ZlibData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZlibData.Marshal(b, m, deterministic)
}
func (dst *ZlibData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZlibData.Merge(dst, src)
}
func (m *ZlibData) XXX_Size() int {
	return xxx_messageInfo_ZlibData.Size(m)
}
func (m *ZlibData) XXX_DiscardUnknown() {
	xxx_messageInfo_ZlibData.DiscardUnknown(m)
}

var xxx_messageInfo_ZlibData proto.InternalMessageInfo

func (m *ZlibData) GetPbData() []*NetPBData {
	if m != nil {
		return m.PbData
	}
	return nil
}

type PackData_S struct {
	Zlibdata             []byte   `protobuf:"bytes,1,opt,name=zlibdata" json:"zlibdata,omitempty"`
	Compress             *bool    `protobuf:"varint,2,opt,name=compress" json:"compress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackData_S) Reset()         { *m = PackData_S{} }
func (m *PackData_S) String() string { return proto.CompactTextString(m) }
func (*PackData_S) ProtoMessage()    {}
func (*PackData_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{7}
}
func (m *PackData_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackData_S.Unmarshal(m, b)
}
func (m *PackData_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackData_S.Marshal(b, m, deterministic)
}
func (dst *PackData_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackData_S.Merge(dst, src)
}
func (m *PackData_S) XXX_Size() int {
	return xxx_messageInfo_PackData_S.Size(m)
}
func (m *PackData_S) XXX_DiscardUnknown() {
	xxx_messageInfo_PackData_S.DiscardUnknown(m)
}

var xxx_messageInfo_PackData_S proto.InternalMessageInfo

func (m *PackData_S) GetZlibdata() []byte {
	if m != nil {
		return m.Zlibdata
	}
	return nil
}

func (m *PackData_S) GetCompress() bool {
	if m != nil && m.Compress != nil {
		return *m.Compress
	}
	return false
}

type GetRoleList_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRoleList_C) Reset()         { *m = GetRoleList_C{} }
func (m *GetRoleList_C) String() string { return proto.CompactTextString(m) }
func (*GetRoleList_C) ProtoMessage()    {}
func (*GetRoleList_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{8}
}
func (m *GetRoleList_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleList_C.Unmarshal(m, b)
}
func (m *GetRoleList_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleList_C.Marshal(b, m, deterministic)
}
func (dst *GetRoleList_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleList_C.Merge(dst, src)
}
func (m *GetRoleList_C) XXX_Size() int {
	return xxx_messageInfo_GetRoleList_C.Size(m)
}
func (m *GetRoleList_C) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleList_C.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleList_C proto.InternalMessageInfo

type GetRoleList_S struct {
	Code                 *Code        `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Roles                []*NetRoleVO `protobuf:"bytes,2,rep,name=roles" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRoleList_S) Reset()         { *m = GetRoleList_S{} }
func (m *GetRoleList_S) String() string { return proto.CompactTextString(m) }
func (*GetRoleList_S) ProtoMessage()    {}
func (*GetRoleList_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Login_a18aa45ac4ce84a4, []int{9}
}
func (m *GetRoleList_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRoleList_S.Unmarshal(m, b)
}
func (m *GetRoleList_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRoleList_S.Marshal(b, m, deterministic)
}
func (dst *GetRoleList_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRoleList_S.Merge(dst, src)
}
func (m *GetRoleList_S) XXX_Size() int {
	return xxx_messageInfo_GetRoleList_S.Size(m)
}
func (m *GetRoleList_S) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRoleList_S.DiscardUnknown(m)
}

var xxx_messageInfo_GetRoleList_S proto.InternalMessageInfo

func (m *GetRoleList_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *GetRoleList_S) GetRoles() []*NetRoleVO {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*Login_C)(nil), "message.Login_C")
	proto.RegisterType((*Login_S)(nil), "message.Login_S")
	proto.RegisterType((*Create_C)(nil), "message.Create_C")
	proto.RegisterType((*Create_S)(nil), "message.Create_S")
	proto.RegisterType((*EnterGame_C)(nil), "message.EnterGame_C")
	proto.RegisterType((*EnterGame_S)(nil), "message.EnterGame_S")
	proto.RegisterType((*ZlibData)(nil), "message.ZlibData")
	proto.RegisterType((*PackData_S)(nil), "message.PackData_S")
	proto.RegisterType((*GetRoleList_C)(nil), "message.GetRoleList_C")
	proto.RegisterType((*GetRoleList_S)(nil), "message.GetRoleList_S")
}

func init() { proto.RegisterFile("Login.proto", fileDescriptor_Login_a18aa45ac4ce84a4) }

var fileDescriptor_Login_a18aa45ac4ce84a4 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6b, 0xdb, 0x3c,
	0x14, 0xc6, 0x4d, 0x9c, 0x38, 0xc7, 0x09, 0x7d, 0x11, 0xe5, 0xc5, 0x84, 0x31, 0x32, 0xb3, 0x0b,
	0xb3, 0x8b, 0x5c, 0xe4, 0x62, 0xf7, 0x8b, 0x3b, 0x4a, 0xa0, 0x4d, 0x8a, 0xb2, 0x75, 0x30, 0x06,
	0x41, 0xb5, 0x4f, 0x52, 0x6d, 0xb1, 0x14, 0x24, 0x65, 0x5b, 0x7b, 0xbd, 0x9f, 0xb6, 0x1f, 0x36,
	0x24, 0x7f, 0xa4, 0xd9, 0xa0, 0xf4, 0xee, 0x3c, 0x1f, 0x96, 0x9e, 0xe7, 0x08, 0x43, 0x78, 0x29,
	0x37, 0x5c, 0x8c, 0x77, 0x4a, 0x1a, 0x49, 0xba, 0x05, 0x6a, 0xcd, 0x36, 0x38, 0xec, 0x4f, 0x99,
	0xc6, 0x9b, 0x45, 0x49, 0xc7, 0xf7, 0xd0, 0x75, 0xae, 0x55, 0x4a, 0x5e, 0x40, 0x8f, 0x65, 0x99,
	0xdc, 0x0b, 0x33, 0xcb, 0x23, 0x6f, 0xe4, 0x25, 0x3d, 0x7a, 0x20, 0xc8, 0x10, 0x02, 0x8d, 0xea,
	0x3b, 0xaa, 0x59, 0x1e, 0x9d, 0x38, 0xb1, 0xc1, 0x24, 0x82, 0x2e, 0x8a, 0x4c, 0xdd, 0xef, 0x4c,
	0xd4, 0x72, 0x52, 0x0d, 0xed, 0x57, 0x5c, 0xa7, 0x77, 0x28, 0xae, 0x78, 0xd4, 0x1e, 0x79, 0x49,
	0x40, 0x1b, 0x1c, 0xff, 0x3a, 0xa9, 0xef, 0x5e, 0x92, 0x57, 0xd0, 0xce, 0x64, 0x8e, 0xee, 0xda,
	0x70, 0x32, 0x18, 0x57, 0x61, 0xc7, 0xa9, 0xcc, 0x91, 0x3a, 0x89, 0x24, 0xd0, 0xde, 0x6b, 0x54,
	0xee, 0xf2, 0x70, 0x72, 0xd6, 0x58, 0xe6, 0x68, 0x3e, 0x6a, 0x54, 0x33, 0xb1, 0x96, 0xd4, 0x39,
	0xc8, 0x4b, 0x80, 0x32, 0xda, 0x07, 0x5e, 0xa0, 0x4b, 0xd4, 0xa2, 0x8f, 0x18, 0x1b, 0x57, 0xc8,
	0x1f, 0x4e, 0x6c, 0x3b, 0xb1, 0x86, 0x24, 0x81, 0xd3, 0x02, 0xd5, 0x06, 0x97, 0x87, 0xcf, 0x7d,
	0xe7, 0xf8, 0x9b, 0x26, 0xaf, 0x61, 0xf0, 0x20, 0x05, 0x2e, 0xd6, 0xeb, 0x2b, 0x2e, 0xf6, 0x06,
	0xa3, 0xce, 0xc8, 0x4b, 0x7c, 0x7a, 0x4c, 0x92, 0x18, 0xfa, 0x5c, 0xcf, 0x11, 0xf3, 0x54, 0x21,
	0x33, 0x18, 0x75, 0xdd, 0x0a, 0x8e, 0xb8, 0xf8, 0xb7, 0x07, 0x41, 0x39, 0xae, 0x52, 0xf2, 0x3f,
	0x74, 0x6c, 0x85, 0xe6, 0x01, 0x2a, 0xf4, 0xe4, 0xf6, 0x87, 0x10, 0x58, 0xd7, 0x9c, 0x55, 0x65,
	0x7b, 0xb4, 0xc1, 0x56, 0xcb, 0xa4, 0x58, 0xf3, 0xcd, 0x2c, 0x77, 0x5d, 0x7d, 0xda, 0xe0, 0x32,
	0xdc, 0xbb, 0xbd, 0x91, 0x55, 0x38, 0xbf, 0x0e, 0x77, 0xe0, 0x6c, 0x9e, 0xaf, 0x9c, 0xdd, 0xed,
	0x79, 0xd5, 0xaf, 0x42, 0xe4, 0x3f, 0x68, 0x69, 0xfc, 0xe9, 0xfa, 0xf8, 0xd4, 0x8e, 0xf1, 0xa7,
	0xa6, 0xc5, 0x73, 0x5f, 0x53, 0xc9, 0x2d, 0x3e, 0xfd, 0x9a, 0xd6, 0x11, 0x0f, 0x20, 0x7c, 0x2f,
	0x0c, 0xaa, 0x0b, 0x56, 0xe0, 0x2a, 0x3d, 0x86, 0xcb, 0xf8, 0x2d, 0x04, 0x9f, 0xb7, 0xfc, 0xf6,
	0x9c, 0x19, 0x46, 0xde, 0x40, 0x67, 0xe7, 0xa6, 0xc8, 0x1b, 0xb5, 0x92, 0x70, 0x42, 0x1e, 0x9f,
	0x7a, 0x3d, 0xb5, 0x0a, 0xad, 0x1c, 0xf1, 0x39, 0xc0, 0x35, 0xcb, 0xbe, 0xd9, 0x79, 0xb5, 0xb4,
	0x6b, 0x7a, 0xd8, 0xf2, 0xdb, 0xbc, 0xfc, 0xd6, 0x4b, 0xfa, 0xb4, 0xc1, 0xe5, 0x0a, 0x8b, 0x9d,
	0x42, 0xad, 0x5d, 0xda, 0x80, 0x36, 0x38, 0x3e, 0x85, 0xc1, 0x05, 0x1a, 0x2a, 0xb7, 0x78, 0xc9,
	0xb5, 0x59, 0xa5, 0xf1, 0x97, 0x63, 0xe2, 0x99, 0xab, 0xf0, 0x6d, 0x51, 0x7b, 0xfa, 0x3f, 0xa9,
	0xed, 0x49, 0x37, 0x0b, 0x5a, 0x1a, 0xa6, 0x67, 0x10, 0x66, 0xb2, 0xa8, 0xf5, 0xa9, 0xef, 0xfe,
	0x9e, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x04, 0xa7, 0x69, 0xe7, 0x03, 0x00, 0x00,
}
