// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PlaceMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlaceInfo struct {
	Mapid                *int32   `protobuf:"varint,1,opt,name=mapid" json:"mapid,omitempty"`
	Guid                 []int64  `protobuf:"varint,2,rep,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceInfo) Reset()         { *m = PlaceInfo{} }
func (m *PlaceInfo) String() string { return proto.CompactTextString(m) }
func (*PlaceInfo) ProtoMessage()    {}
func (*PlaceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_PlaceMsg_18e28080db2851fe, []int{0}
}
func (m *PlaceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceInfo.Unmarshal(m, b)
}
func (m *PlaceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceInfo.Marshal(b, m, deterministic)
}
func (dst *PlaceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceInfo.Merge(dst, src)
}
func (m *PlaceInfo) XXX_Size() int {
	return xxx_messageInfo_PlaceInfo.Size(m)
}
func (m *PlaceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceInfo proto.InternalMessageInfo

func (m *PlaceInfo) GetMapid() int32 {
	if m != nil && m.Mapid != nil {
		return *m.Mapid
	}
	return 0
}

func (m *PlaceInfo) GetGuid() []int64 {
	if m != nil {
		return m.Guid
	}
	return nil
}

type PlaceInfo_C struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceInfo_C) Reset()         { *m = PlaceInfo_C{} }
func (m *PlaceInfo_C) String() string { return proto.CompactTextString(m) }
func (*PlaceInfo_C) ProtoMessage()    {}
func (*PlaceInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_PlaceMsg_18e28080db2851fe, []int{1}
}
func (m *PlaceInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceInfo_C.Unmarshal(m, b)
}
func (m *PlaceInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceInfo_C.Marshal(b, m, deterministic)
}
func (dst *PlaceInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceInfo_C.Merge(dst, src)
}
func (m *PlaceInfo_C) XXX_Size() int {
	return xxx_messageInfo_PlaceInfo_C.Size(m)
}
func (m *PlaceInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceInfo_C proto.InternalMessageInfo

type PlaceInfo_S struct {
	Infos                []*PlaceInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlaceInfo_S) Reset()         { *m = PlaceInfo_S{} }
func (m *PlaceInfo_S) String() string { return proto.CompactTextString(m) }
func (*PlaceInfo_S) ProtoMessage()    {}
func (*PlaceInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_PlaceMsg_18e28080db2851fe, []int{2}
}
func (m *PlaceInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceInfo_S.Unmarshal(m, b)
}
func (m *PlaceInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceInfo_S.Marshal(b, m, deterministic)
}
func (dst *PlaceInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceInfo_S.Merge(dst, src)
}
func (m *PlaceInfo_S) XXX_Size() int {
	return xxx_messageInfo_PlaceInfo_S.Size(m)
}
func (m *PlaceInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceInfo_S proto.InternalMessageInfo

func (m *PlaceInfo_S) GetInfos() []*PlaceInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type PlaceRole_C struct {
	Infos                *PlaceInfo `protobuf:"bytes,1,opt,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlaceRole_C) Reset()         { *m = PlaceRole_C{} }
func (m *PlaceRole_C) String() string { return proto.CompactTextString(m) }
func (*PlaceRole_C) ProtoMessage()    {}
func (*PlaceRole_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_PlaceMsg_18e28080db2851fe, []int{3}
}
func (m *PlaceRole_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceRole_C.Unmarshal(m, b)
}
func (m *PlaceRole_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceRole_C.Marshal(b, m, deterministic)
}
func (dst *PlaceRole_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceRole_C.Merge(dst, src)
}
func (m *PlaceRole_C) XXX_Size() int {
	return xxx_messageInfo_PlaceRole_C.Size(m)
}
func (m *PlaceRole_C) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceRole_C.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceRole_C proto.InternalMessageInfo

func (m *PlaceRole_C) GetInfos() *PlaceInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type PlaceRole_S struct {
	Code                 *Code        `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Infos                []*PlaceInfo `protobuf:"bytes,2,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlaceRole_S) Reset()         { *m = PlaceRole_S{} }
func (m *PlaceRole_S) String() string { return proto.CompactTextString(m) }
func (*PlaceRole_S) ProtoMessage()    {}
func (*PlaceRole_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_PlaceMsg_18e28080db2851fe, []int{4}
}
func (m *PlaceRole_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceRole_S.Unmarshal(m, b)
}
func (m *PlaceRole_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceRole_S.Marshal(b, m, deterministic)
}
func (dst *PlaceRole_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceRole_S.Merge(dst, src)
}
func (m *PlaceRole_S) XXX_Size() int {
	return xxx_messageInfo_PlaceRole_S.Size(m)
}
func (m *PlaceRole_S) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceRole_S.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceRole_S proto.InternalMessageInfo

func (m *PlaceRole_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *PlaceRole_S) GetInfos() []*PlaceInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*PlaceInfo)(nil), "message.PlaceInfo")
	proto.RegisterType((*PlaceInfo_C)(nil), "message.PlaceInfo_C")
	proto.RegisterType((*PlaceInfo_S)(nil), "message.PlaceInfo_S")
	proto.RegisterType((*PlaceRole_C)(nil), "message.PlaceRole_C")
	proto.RegisterType((*PlaceRole_S)(nil), "message.PlaceRole_S")
}

func init() { proto.RegisterFile("PlaceMsg.proto", fileDescriptor_PlaceMsg_18e28080db2851fe) }

var fileDescriptor_PlaceMsg_18e28080db2851fe = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0xc8, 0x49, 0x4c,
	0x4e, 0xf5, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87, 0x08, 0x2b, 0x99, 0x72,
	0x71, 0x82, 0x15, 0x7a, 0xe6, 0xa5, 0xe5, 0x0b, 0x89, 0x70, 0xb1, 0xe6, 0x26, 0x16, 0x64, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x38, 0x42, 0x42, 0x5c, 0x2c, 0xe9, 0xa5, 0x99,
	0x29, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xcc, 0x41, 0x60, 0xb6, 0x12, 0x2f, 0x17, 0x37, 0x5c, 0x5b,
	0xbc, 0xb3, 0x92, 0x39, 0x32, 0x37, 0x58, 0x48, 0x83, 0x8b, 0x35, 0x33, 0x2f, 0x2d, 0xbf, 0x58,
	0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x48, 0x0f, 0x6a, 0xb7, 0x1e, 0x5c, 0x51, 0x10, 0x44,
	0x01, 0x5c, 0x63, 0x50, 0x7e, 0x4e, 0x6a, 0xbc, 0x33, 0xb2, 0x46, 0x46, 0xfc, 0x1a, 0xa3, 0x90,
	0x35, 0x06, 0x0b, 0x29, 0x72, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x42, 0xf5, 0xf1, 0xc2, 0xf5, 0x39,
	0xe7, 0xa7, 0xa4, 0x06, 0x81, 0xa5, 0x10, 0x66, 0x33, 0x11, 0x70, 0x94, 0x93, 0x38, 0x17, 0x77,
	0x72, 0x7e, 0x2e, 0x4c, 0xde, 0x89, 0x03, 0x16, 0x92, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0x9f, 0x7a, 0xac, 0x54, 0x01, 0x00, 0x00,
}
