// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RoleIndexMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Recruit_C struct {
	ConfigId             *int32   `protobuf:"varint,1,opt,name=configId" json:"configId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recruit_C) Reset()         { *m = Recruit_C{} }
func (m *Recruit_C) String() string { return proto.CompactTextString(m) }
func (*Recruit_C) ProtoMessage()    {}
func (*Recruit_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{0}
}
func (m *Recruit_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recruit_C.Unmarshal(m, b)
}
func (m *Recruit_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recruit_C.Marshal(b, m, deterministic)
}
func (dst *Recruit_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recruit_C.Merge(dst, src)
}
func (m *Recruit_C) XXX_Size() int {
	return xxx_messageInfo_Recruit_C.Size(m)
}
func (m *Recruit_C) XXX_DiscardUnknown() {
	xxx_messageInfo_Recruit_C.DiscardUnknown(m)
}

var xxx_messageInfo_Recruit_C proto.InternalMessageInfo

func (m *Recruit_C) GetConfigId() int32 {
	if m != nil && m.ConfigId != nil {
		return *m.ConfigId
	}
	return 0
}

type Recruit_S struct {
	Code                 *Code      `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	RoleVo               *NetRoleVO `protobuf:"bytes,2,opt,name=roleVo" json:"roleVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Recruit_S) Reset()         { *m = Recruit_S{} }
func (m *Recruit_S) String() string { return proto.CompactTextString(m) }
func (*Recruit_S) ProtoMessage()    {}
func (*Recruit_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{1}
}
func (m *Recruit_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recruit_S.Unmarshal(m, b)
}
func (m *Recruit_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recruit_S.Marshal(b, m, deterministic)
}
func (dst *Recruit_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recruit_S.Merge(dst, src)
}
func (m *Recruit_S) XXX_Size() int {
	return xxx_messageInfo_Recruit_S.Size(m)
}
func (m *Recruit_S) XXX_DiscardUnknown() {
	xxx_messageInfo_Recruit_S.DiscardUnknown(m)
}

var xxx_messageInfo_Recruit_S proto.InternalMessageInfo

func (m *Recruit_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Recruit_S) GetRoleVo() *NetRoleVO {
	if m != nil {
		return m.RoleVo
	}
	return nil
}

type BattleInfo struct {
	TargetGuid           *int64   `protobuf:"varint,1,opt,name=targetGuid" json:"targetGuid,omitempty"`
	Index                *int32   `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BattleInfo) Reset()         { *m = BattleInfo{} }
func (m *BattleInfo) String() string { return proto.CompactTextString(m) }
func (*BattleInfo) ProtoMessage()    {}
func (*BattleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{2}
}
func (m *BattleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BattleInfo.Unmarshal(m, b)
}
func (m *BattleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BattleInfo.Marshal(b, m, deterministic)
}
func (dst *BattleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BattleInfo.Merge(dst, src)
}
func (m *BattleInfo) XXX_Size() int {
	return xxx_messageInfo_BattleInfo.Size(m)
}
func (m *BattleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BattleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BattleInfo proto.InternalMessageInfo

func (m *BattleInfo) GetTargetGuid() int64 {
	if m != nil && m.TargetGuid != nil {
		return *m.TargetGuid
	}
	return 0
}

func (m *BattleInfo) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type UpBattle_C struct {
	Infos                []*BattleInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpBattle_C) Reset()         { *m = UpBattle_C{} }
func (m *UpBattle_C) String() string { return proto.CompactTextString(m) }
func (*UpBattle_C) ProtoMessage()    {}
func (*UpBattle_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{3}
}
func (m *UpBattle_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpBattle_C.Unmarshal(m, b)
}
func (m *UpBattle_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpBattle_C.Marshal(b, m, deterministic)
}
func (dst *UpBattle_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpBattle_C.Merge(dst, src)
}
func (m *UpBattle_C) XXX_Size() int {
	return xxx_messageInfo_UpBattle_C.Size(m)
}
func (m *UpBattle_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UpBattle_C.DiscardUnknown(m)
}

var xxx_messageInfo_UpBattle_C proto.InternalMessageInfo

func (m *UpBattle_C) GetInfos() []*BattleInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type UpBatte_S struct {
	Code                 *Code         `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Infos                []*BattleInfo `protobuf:"bytes,2,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpBatte_S) Reset()         { *m = UpBatte_S{} }
func (m *UpBatte_S) String() string { return proto.CompactTextString(m) }
func (*UpBatte_S) ProtoMessage()    {}
func (*UpBatte_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{4}
}
func (m *UpBatte_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpBatte_S.Unmarshal(m, b)
}
func (m *UpBatte_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpBatte_S.Marshal(b, m, deterministic)
}
func (dst *UpBatte_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpBatte_S.Merge(dst, src)
}
func (m *UpBatte_S) XXX_Size() int {
	return xxx_messageInfo_UpBatte_S.Size(m)
}
func (m *UpBatte_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UpBatte_S.DiscardUnknown(m)
}

var xxx_messageInfo_UpBatte_S proto.InternalMessageInfo

func (m *UpBatte_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpBatte_S) GetInfos() []*BattleInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type UpHeroLevel_C struct {
	Type                 *int32   `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Guid                 *int64   `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	IsAuto               *bool    `protobuf:"varint,3,opt,name=isAuto" json:"isAuto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroLevel_C) Reset()         { *m = UpHeroLevel_C{} }
func (m *UpHeroLevel_C) String() string { return proto.CompactTextString(m) }
func (*UpHeroLevel_C) ProtoMessage()    {}
func (*UpHeroLevel_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{5}
}
func (m *UpHeroLevel_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroLevel_C.Unmarshal(m, b)
}
func (m *UpHeroLevel_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroLevel_C.Marshal(b, m, deterministic)
}
func (dst *UpHeroLevel_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroLevel_C.Merge(dst, src)
}
func (m *UpHeroLevel_C) XXX_Size() int {
	return xxx_messageInfo_UpHeroLevel_C.Size(m)
}
func (m *UpHeroLevel_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroLevel_C.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroLevel_C proto.InternalMessageInfo

func (m *UpHeroLevel_C) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *UpHeroLevel_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroLevel_C) GetIsAuto() bool {
	if m != nil && m.IsAuto != nil {
		return *m.IsAuto
	}
	return false
}

type UpHeroLevel_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroLevel_S) Reset()         { *m = UpHeroLevel_S{} }
func (m *UpHeroLevel_S) String() string { return proto.CompactTextString(m) }
func (*UpHeroLevel_S) ProtoMessage()    {}
func (*UpHeroLevel_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{6}
}
func (m *UpHeroLevel_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroLevel_S.Unmarshal(m, b)
}
func (m *UpHeroLevel_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroLevel_S.Marshal(b, m, deterministic)
}
func (dst *UpHeroLevel_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroLevel_S.Merge(dst, src)
}
func (m *UpHeroLevel_S) XXX_Size() int {
	return xxx_messageInfo_UpHeroLevel_S.Size(m)
}
func (m *UpHeroLevel_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroLevel_S.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroLevel_S proto.InternalMessageInfo

func (m *UpHeroLevel_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

type UpHeroStar_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroStar_C) Reset()         { *m = UpHeroStar_C{} }
func (m *UpHeroStar_C) String() string { return proto.CompactTextString(m) }
func (*UpHeroStar_C) ProtoMessage()    {}
func (*UpHeroStar_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{7}
}
func (m *UpHeroStar_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroStar_C.Unmarshal(m, b)
}
func (m *UpHeroStar_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroStar_C.Marshal(b, m, deterministic)
}
func (dst *UpHeroStar_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroStar_C.Merge(dst, src)
}
func (m *UpHeroStar_C) XXX_Size() int {
	return xxx_messageInfo_UpHeroStar_C.Size(m)
}
func (m *UpHeroStar_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroStar_C.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroStar_C proto.InternalMessageInfo

func (m *UpHeroStar_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

type UpHeroStar_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Guid                 *int64   `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	StarId               *int32   `protobuf:"varint,3,opt,name=starId" json:"starId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroStar_S) Reset()         { *m = UpHeroStar_S{} }
func (m *UpHeroStar_S) String() string { return proto.CompactTextString(m) }
func (*UpHeroStar_S) ProtoMessage()    {}
func (*UpHeroStar_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{8}
}
func (m *UpHeroStar_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroStar_S.Unmarshal(m, b)
}
func (m *UpHeroStar_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroStar_S.Marshal(b, m, deterministic)
}
func (dst *UpHeroStar_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroStar_S.Merge(dst, src)
}
func (m *UpHeroStar_S) XXX_Size() int {
	return xxx_messageInfo_UpHeroStar_S.Size(m)
}
func (m *UpHeroStar_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroStar_S.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroStar_S proto.InternalMessageInfo

func (m *UpHeroStar_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpHeroStar_S) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroStar_S) GetStarId() int32 {
	if m != nil && m.StarId != nil {
		return *m.StarId
	}
	return 0
}

type UpHeroQuality_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	IsAuto               *bool    `protobuf:"varint,2,opt,name=isAuto" json:"isAuto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroQuality_C) Reset()         { *m = UpHeroQuality_C{} }
func (m *UpHeroQuality_C) String() string { return proto.CompactTextString(m) }
func (*UpHeroQuality_C) ProtoMessage()    {}
func (*UpHeroQuality_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{9}
}
func (m *UpHeroQuality_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroQuality_C.Unmarshal(m, b)
}
func (m *UpHeroQuality_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroQuality_C.Marshal(b, m, deterministic)
}
func (dst *UpHeroQuality_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroQuality_C.Merge(dst, src)
}
func (m *UpHeroQuality_C) XXX_Size() int {
	return xxx_messageInfo_UpHeroQuality_C.Size(m)
}
func (m *UpHeroQuality_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroQuality_C.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroQuality_C proto.InternalMessageInfo

func (m *UpHeroQuality_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroQuality_C) GetIsAuto() bool {
	if m != nil && m.IsAuto != nil {
		return *m.IsAuto
	}
	return false
}

type UpHeroQuality_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Guid                 *int64   `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Quality              *int32   `protobuf:"varint,3,opt,name=quality" json:"quality,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroQuality_S) Reset()         { *m = UpHeroQuality_S{} }
func (m *UpHeroQuality_S) String() string { return proto.CompactTextString(m) }
func (*UpHeroQuality_S) ProtoMessage()    {}
func (*UpHeroQuality_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{10}
}
func (m *UpHeroQuality_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroQuality_S.Unmarshal(m, b)
}
func (m *UpHeroQuality_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroQuality_S.Marshal(b, m, deterministic)
}
func (dst *UpHeroQuality_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroQuality_S.Merge(dst, src)
}
func (m *UpHeroQuality_S) XXX_Size() int {
	return xxx_messageInfo_UpHeroQuality_S.Size(m)
}
func (m *UpHeroQuality_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroQuality_S.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroQuality_S proto.InternalMessageInfo

func (m *UpHeroQuality_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpHeroQuality_S) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroQuality_S) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

type UpHeroXiuXing_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	Type                 *int32   `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	OneAttrKey           *string  `protobuf:"bytes,3,opt,name=oneAttrKey" json:"oneAttrKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpHeroXiuXing_C) Reset()         { *m = UpHeroXiuXing_C{} }
func (m *UpHeroXiuXing_C) String() string { return proto.CompactTextString(m) }
func (*UpHeroXiuXing_C) ProtoMessage()    {}
func (*UpHeroXiuXing_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{11}
}
func (m *UpHeroXiuXing_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroXiuXing_C.Unmarshal(m, b)
}
func (m *UpHeroXiuXing_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroXiuXing_C.Marshal(b, m, deterministic)
}
func (dst *UpHeroXiuXing_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroXiuXing_C.Merge(dst, src)
}
func (m *UpHeroXiuXing_C) XXX_Size() int {
	return xxx_messageInfo_UpHeroXiuXing_C.Size(m)
}
func (m *UpHeroXiuXing_C) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroXiuXing_C.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroXiuXing_C proto.InternalMessageInfo

func (m *UpHeroXiuXing_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroXiuXing_C) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *UpHeroXiuXing_C) GetOneAttrKey() string {
	if m != nil && m.OneAttrKey != nil {
		return *m.OneAttrKey
	}
	return ""
}

type UpHeroXiuXing_S struct {
	Code                 *Code           `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Guid                 *int64          `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	AttrInfos            []*NetAttrInfos `protobuf:"bytes,3,rep,name=AttrInfos" json:"AttrInfos,omitempty"`
	Type                 *int64          `protobuf:"varint,4,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UpHeroXiuXing_S) Reset()         { *m = UpHeroXiuXing_S{} }
func (m *UpHeroXiuXing_S) String() string { return proto.CompactTextString(m) }
func (*UpHeroXiuXing_S) ProtoMessage()    {}
func (*UpHeroXiuXing_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7, []int{12}
}
func (m *UpHeroXiuXing_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpHeroXiuXing_S.Unmarshal(m, b)
}
func (m *UpHeroXiuXing_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpHeroXiuXing_S.Marshal(b, m, deterministic)
}
func (dst *UpHeroXiuXing_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpHeroXiuXing_S.Merge(dst, src)
}
func (m *UpHeroXiuXing_S) XXX_Size() int {
	return xxx_messageInfo_UpHeroXiuXing_S.Size(m)
}
func (m *UpHeroXiuXing_S) XXX_DiscardUnknown() {
	xxx_messageInfo_UpHeroXiuXing_S.DiscardUnknown(m)
}

var xxx_messageInfo_UpHeroXiuXing_S proto.InternalMessageInfo

func (m *UpHeroXiuXing_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *UpHeroXiuXing_S) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

func (m *UpHeroXiuXing_S) GetAttrInfos() []*NetAttrInfos {
	if m != nil {
		return m.AttrInfos
	}
	return nil
}

func (m *UpHeroXiuXing_S) GetType() int64 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Recruit_C)(nil), "message.Recruit_C")
	proto.RegisterType((*Recruit_S)(nil), "message.Recruit_S")
	proto.RegisterType((*BattleInfo)(nil), "message.BattleInfo")
	proto.RegisterType((*UpBattle_C)(nil), "message.UpBattle_C")
	proto.RegisterType((*UpBatte_S)(nil), "message.UpBatte_S")
	proto.RegisterType((*UpHeroLevel_C)(nil), "message.UpHeroLevel_C")
	proto.RegisterType((*UpHeroLevel_S)(nil), "message.UpHeroLevel_S")
	proto.RegisterType((*UpHeroStar_C)(nil), "message.UpHeroStar_C")
	proto.RegisterType((*UpHeroStar_S)(nil), "message.UpHeroStar_S")
	proto.RegisterType((*UpHeroQuality_C)(nil), "message.UpHeroQuality_C")
	proto.RegisterType((*UpHeroQuality_S)(nil), "message.UpHeroQuality_S")
	proto.RegisterType((*UpHeroXiuXing_C)(nil), "message.UpHeroXiuXing_C")
	proto.RegisterType((*UpHeroXiuXing_S)(nil), "message.UpHeroXiuXing_S")
}

func init() { proto.RegisterFile("RoleIndexMsg.proto", fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7) }

var fileDescriptor_RoleIndexMsg_9ef7162a850f7ee7 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6b, 0xdb, 0x30,
	0x14, 0xc7, 0xb1, 0x93, 0xb4, 0xcd, 0x4b, 0xca, 0x40, 0xfb, 0x81, 0xe9, 0xa0, 0x64, 0xba, 0x2c,
	0xdb, 0x21, 0x87, 0xec, 0xb0, 0xd3, 0x0e, 0xb5, 0x0f, 0x9b, 0xd9, 0x8f, 0x30, 0x95, 0x86, 0x76,
	0x30, 0x82, 0x67, 0xbf, 0x18, 0x81, 0x6b, 0x79, 0xb2, 0x3c, 0xd6, 0x3f, 0x63, 0xff, 0xf1, 0x90,
	0xe4, 0x5f, 0x29, 0x2b, 0x0b, 0xb9, 0xbd, 0xf7, 0xf4, 0x7d, 0x5f, 0x7d, 0x9e, 0x24, 0x1b, 0x08,
	0x13, 0x19, 0x86, 0x79, 0x82, 0xbf, 0x3f, 0x97, 0xe9, 0xa2, 0x90, 0x42, 0x09, 0x72, 0x7c, 0x8b,
	0x65, 0x19, 0xa5, 0x78, 0x36, 0xf5, 0xa3, 0x12, 0xd7, 0x2b, 0x5b, 0xa6, 0x2f, 0x61, 0xcc, 0x30,
	0x96, 0x15, 0x57, 0x9b, 0x80, 0x9c, 0xc1, 0x49, 0x2c, 0xf2, 0x2d, 0x4f, 0xc3, 0xc4, 0x73, 0x66,
	0xce, 0x7c, 0xc4, 0xda, 0x9c, 0x7e, 0xeb, 0x84, 0x97, 0xe4, 0x05, 0x0c, 0x63, 0x91, 0xa0, 0x11,
	0x4d, 0x96, 0xa7, 0x8b, 0xda, 0x7b, 0x11, 0x88, 0x04, 0x99, 0x59, 0x22, 0xaf, 0xe1, 0x48, 0x8a,
	0x0c, 0xd7, 0xc2, 0x73, 0x8d, 0x88, 0xb4, 0xa2, 0x2f, 0xa8, 0x34, 0xdf, 0x7a, 0xc5, 0x6a, 0x05,
	0xf5, 0x01, 0xfc, 0x48, 0x29, 0xcd, 0xbc, 0x15, 0xe4, 0x1c, 0x40, 0x45, 0x32, 0x45, 0xf5, 0xbe,
	0xe2, 0x96, 0x63, 0xc0, 0x7a, 0x15, 0xf2, 0x04, 0x46, 0x5c, 0xcf, 0x66, 0x8c, 0x47, 0xcc, 0x26,
	0xf4, 0x2d, 0xc0, 0x55, 0x61, 0x5d, 0x36, 0x01, 0x79, 0xa5, 0x35, 0x5b, 0x51, 0x7a, 0xce, 0x6c,
	0x30, 0x9f, 0x2c, 0x1f, 0xb7, 0x9b, 0x77, 0xfb, 0x30, 0xab, 0xa0, 0x37, 0x30, 0xb6, 0x8d, 0xb8,
	0xdf, 0x60, 0xad, 0xb5, 0xfb, 0x5f, 0xeb, 0x15, 0x9c, 0x5e, 0x15, 0x1f, 0x50, 0x8a, 0x4f, 0xf8,
	0x0b, 0xb3, 0x4d, 0x40, 0x08, 0x0c, 0xd5, 0x5d, 0x81, 0xf5, 0xe1, 0x9a, 0x58, 0xd7, 0x52, 0x3d,
	0xa8, 0x6b, 0x06, 0x35, 0x31, 0x79, 0x06, 0x47, 0xbc, 0xbc, 0xa8, 0x94, 0xf0, 0x06, 0x33, 0x67,
	0x7e, 0xc2, 0xea, 0x8c, 0x2e, 0x77, 0x0d, 0xf7, 0xe1, 0xa5, 0x14, 0xa6, 0xb6, 0xe7, 0x52, 0x45,
	0xd2, 0x32, 0xa4, 0xdd, 0xc1, 0x9a, 0x98, 0x7e, 0xdf, 0xd1, 0xec, 0x75, 0x0c, 0x0f, 0x60, 0x97,
	0x2a, 0x92, 0x61, 0x62, 0xb0, 0x47, 0xac, 0xce, 0xe8, 0x3b, 0x78, 0x64, 0xed, 0xbf, 0x56, 0x51,
	0xc6, 0xd5, 0xdd, 0xbf, 0x29, 0x7a, 0x53, 0xbb, 0x3b, 0x53, 0xff, 0xb8, 0xdf, 0x7e, 0x30, 0xa0,
	0x07, 0xc7, 0x3f, 0xad, 0x47, 0x4d, 0xd8, 0xa4, 0xf4, 0xa6, 0xd9, 0xe3, 0x9a, 0x57, 0xd7, 0x3c,
	0x4f, 0x1f, 0x40, 0x6c, 0x2e, 0xd0, 0xed, 0x5d, 0xe0, 0x39, 0x80, 0xc8, 0xf1, 0x42, 0x29, 0xf9,
	0x11, 0xad, 0xef, 0x98, 0xf5, 0x2a, 0xf4, 0x8f, 0x73, 0xdf, 0xfb, 0x60, 0xfe, 0x37, 0x30, 0xd6,
	0xae, 0xa1, 0x79, 0x7f, 0x03, 0xf3, 0xfe, 0x9e, 0xf6, 0xbf, 0xab, 0x76, 0x91, 0x75, 0xba, 0x96,
	0x79, 0x68, 0x8d, 0x74, 0xec, 0x3f, 0x87, 0x49, 0x2c, 0x6e, 0x9b, 0x56, 0x7f, 0xda, 0xff, 0x61,
	0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xe5, 0x5d, 0xf8, 0x3f, 0x04, 0x00, 0x00,
}
