// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RoleEquipMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChangeEquip_C struct {
	HeroGuid             *int64   `protobuf:"varint,1,opt,name=heroGuid" json:"heroGuid,omitempty"`
	ItemGuid             *int64   `protobuf:"varint,2,opt,name=itemGuid" json:"itemGuid,omitempty"`
	Slot                 *int32   `protobuf:"varint,3,opt,name=slot" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeEquip_C) Reset()         { *m = ChangeEquip_C{} }
func (m *ChangeEquip_C) String() string { return proto.CompactTextString(m) }
func (*ChangeEquip_C) ProtoMessage()    {}
func (*ChangeEquip_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510, []int{0}
}
func (m *ChangeEquip_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEquip_C.Unmarshal(m, b)
}
func (m *ChangeEquip_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEquip_C.Marshal(b, m, deterministic)
}
func (dst *ChangeEquip_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEquip_C.Merge(dst, src)
}
func (m *ChangeEquip_C) XXX_Size() int {
	return xxx_messageInfo_ChangeEquip_C.Size(m)
}
func (m *ChangeEquip_C) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEquip_C.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEquip_C proto.InternalMessageInfo

func (m *ChangeEquip_C) GetHeroGuid() int64 {
	if m != nil && m.HeroGuid != nil {
		return *m.HeroGuid
	}
	return 0
}

func (m *ChangeEquip_C) GetItemGuid() int64 {
	if m != nil && m.ItemGuid != nil {
		return *m.ItemGuid
	}
	return 0
}

func (m *ChangeEquip_C) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

type ChangeEquip_S struct {
	Code                 *Code       `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	HeroGuid             *int64      `protobuf:"varint,2,opt,name=heroGuid" json:"heroGuid,omitempty"`
	Slot                 *int32      `protobuf:"varint,3,opt,name=slot" json:"slot,omitempty"`
	EquipVo              *NetEquipVo `protobuf:"bytes,4,opt,name=equipVo" json:"equipVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangeEquip_S) Reset()         { *m = ChangeEquip_S{} }
func (m *ChangeEquip_S) String() string { return proto.CompactTextString(m) }
func (*ChangeEquip_S) ProtoMessage()    {}
func (*ChangeEquip_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510, []int{1}
}
func (m *ChangeEquip_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeEquip_S.Unmarshal(m, b)
}
func (m *ChangeEquip_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeEquip_S.Marshal(b, m, deterministic)
}
func (dst *ChangeEquip_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeEquip_S.Merge(dst, src)
}
func (m *ChangeEquip_S) XXX_Size() int {
	return xxx_messageInfo_ChangeEquip_S.Size(m)
}
func (m *ChangeEquip_S) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeEquip_S.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeEquip_S proto.InternalMessageInfo

func (m *ChangeEquip_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *ChangeEquip_S) GetHeroGuid() int64 {
	if m != nil && m.HeroGuid != nil {
		return *m.HeroGuid
	}
	return 0
}

func (m *ChangeEquip_S) GetSlot() int32 {
	if m != nil && m.Slot != nil {
		return *m.Slot
	}
	return 0
}

func (m *ChangeEquip_S) GetEquipVo() *NetEquipVo {
	if m != nil {
		return m.EquipVo
	}
	return nil
}

type QiangHuaEquip_C struct {
	HeroGuid             *int64   `protobuf:"varint,1,opt,name=heroGuid" json:"heroGuid,omitempty"`
	ItemGuid             *int64   `protobuf:"varint,2,opt,name=itemGuid" json:"itemGuid,omitempty"`
	Onekey               *bool    `protobuf:"varint,3,opt,name=onekey" json:"onekey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QiangHuaEquip_C) Reset()         { *m = QiangHuaEquip_C{} }
func (m *QiangHuaEquip_C) String() string { return proto.CompactTextString(m) }
func (*QiangHuaEquip_C) ProtoMessage()    {}
func (*QiangHuaEquip_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510, []int{2}
}
func (m *QiangHuaEquip_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QiangHuaEquip_C.Unmarshal(m, b)
}
func (m *QiangHuaEquip_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QiangHuaEquip_C.Marshal(b, m, deterministic)
}
func (dst *QiangHuaEquip_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QiangHuaEquip_C.Merge(dst, src)
}
func (m *QiangHuaEquip_C) XXX_Size() int {
	return xxx_messageInfo_QiangHuaEquip_C.Size(m)
}
func (m *QiangHuaEquip_C) XXX_DiscardUnknown() {
	xxx_messageInfo_QiangHuaEquip_C.DiscardUnknown(m)
}

var xxx_messageInfo_QiangHuaEquip_C proto.InternalMessageInfo

func (m *QiangHuaEquip_C) GetHeroGuid() int64 {
	if m != nil && m.HeroGuid != nil {
		return *m.HeroGuid
	}
	return 0
}

func (m *QiangHuaEquip_C) GetItemGuid() int64 {
	if m != nil && m.ItemGuid != nil {
		return *m.ItemGuid
	}
	return 0
}

func (m *QiangHuaEquip_C) GetOnekey() bool {
	if m != nil && m.Onekey != nil {
		return *m.Onekey
	}
	return false
}

type QiangHuaEquip_S struct {
	Code                 *Code         `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	HeroGuid             *int64        `protobuf:"varint,2,opt,name=heroGuid" json:"heroGuid,omitempty"`
	EquipVo              []*NetEquipVo `protobuf:"bytes,3,rep,name=equipVo" json:"equipVo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QiangHuaEquip_S) Reset()         { *m = QiangHuaEquip_S{} }
func (m *QiangHuaEquip_S) String() string { return proto.CompactTextString(m) }
func (*QiangHuaEquip_S) ProtoMessage()    {}
func (*QiangHuaEquip_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510, []int{3}
}
func (m *QiangHuaEquip_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QiangHuaEquip_S.Unmarshal(m, b)
}
func (m *QiangHuaEquip_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QiangHuaEquip_S.Marshal(b, m, deterministic)
}
func (dst *QiangHuaEquip_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QiangHuaEquip_S.Merge(dst, src)
}
func (m *QiangHuaEquip_S) XXX_Size() int {
	return xxx_messageInfo_QiangHuaEquip_S.Size(m)
}
func (m *QiangHuaEquip_S) XXX_DiscardUnknown() {
	xxx_messageInfo_QiangHuaEquip_S.DiscardUnknown(m)
}

var xxx_messageInfo_QiangHuaEquip_S proto.InternalMessageInfo

func (m *QiangHuaEquip_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *QiangHuaEquip_S) GetHeroGuid() int64 {
	if m != nil && m.HeroGuid != nil {
		return *m.HeroGuid
	}
	return 0
}

func (m *QiangHuaEquip_S) GetEquipVo() []*NetEquipVo {
	if m != nil {
		return m.EquipVo
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeEquip_C)(nil), "message.ChangeEquip_C")
	proto.RegisterType((*ChangeEquip_S)(nil), "message.ChangeEquip_S")
	proto.RegisterType((*QiangHuaEquip_C)(nil), "message.QiangHuaEquip_C")
	proto.RegisterType((*QiangHuaEquip_S)(nil), "message.QiangHuaEquip_S")
}

func init() { proto.RegisterFile("RoleEquipMsg.proto", fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510) }

var fileDescriptor_RoleEquipMsg_4c1bfafcc2ac8510 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0xca, 0xcf, 0x49,
	0x75, 0x2d, 0x2c, 0xcd, 0x2c, 0xf0, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87,
	0x08, 0x2b, 0x45, 0x73, 0xf1, 0x3a, 0x67, 0x24, 0xe6, 0xa5, 0x43, 0x94, 0xc7, 0x3b, 0x0b, 0x49,
	0x71, 0x71, 0x64, 0xa4, 0x16, 0xe5, 0xbb, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30,
	0x07, 0xc1, 0xf9, 0x20, 0xb9, 0xcc, 0x92, 0xd4, 0x5c, 0xb0, 0x1c, 0x13, 0x44, 0x0e, 0xc6, 0x17,
	0x12, 0xe2, 0x62, 0x29, 0xce, 0xc9, 0x2f, 0x91, 0x60, 0x56, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3,
	0x95, 0x26, 0x32, 0xa2, 0x9a, 0x1e, 0x2c, 0xa4, 0xc8, 0xc5, 0x92, 0x9c, 0x9f, 0x92, 0x0a, 0x36,
	0x99, 0xdb, 0x88, 0x57, 0x0f, 0xea, 0x28, 0x3d, 0xe7, 0xfc, 0x94, 0xd4, 0x20, 0xb0, 0x14, 0x8a,
	0x03, 0x98, 0xd0, 0x1c, 0x80, 0xc5, 0x12, 0x21, 0x5d, 0x2e, 0xf6, 0x54, 0x90, 0xe9, 0x61, 0xf9,
	0x12, 0x2c, 0x60, 0x53, 0x85, 0xe1, 0xa6, 0xfa, 0xa5, 0x96, 0xb8, 0x42, 0xa4, 0x82, 0x60, 0x6a,
	0x94, 0x12, 0xb9, 0xf8, 0x03, 0x33, 0x13, 0xf3, 0xd2, 0x3d, 0x4a, 0x13, 0x29, 0xf5, 0xb2, 0x18,
	0x17, 0x5b, 0x7e, 0x5e, 0x6a, 0x76, 0x6a, 0x25, 0xd8, 0x3d, 0x1c, 0x41, 0x50, 0x9e, 0x52, 0x3d,
	0xba, 0x15, 0x14, 0xfb, 0x1b, 0xc9, 0x8f, 0xcc, 0x0a, 0xcc, 0x84, 0xfc, 0xe8, 0x24, 0xcd, 0xc5,
	0x9d, 0x9c, 0x9f, 0x0b, 0x53, 0xe2, 0xc4, 0x83, 0x9c, 0x1c, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xda, 0x23, 0xf0, 0x82, 0x1d, 0x02, 0x00, 0x00,
}
