// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Skill.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SkillInfo_C struct {
	Guid                 *int64   `protobuf:"varint,1,opt,name=guid" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillInfo_C) Reset()         { *m = SkillInfo_C{} }
func (m *SkillInfo_C) String() string { return proto.CompactTextString(m) }
func (*SkillInfo_C) ProtoMessage()    {}
func (*SkillInfo_C) Descriptor() ([]byte, []int) {
	return fileDescriptor_Skill_fb39a603eab4eb9d, []int{0}
}
func (m *SkillInfo_C) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillInfo_C.Unmarshal(m, b)
}
func (m *SkillInfo_C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillInfo_C.Marshal(b, m, deterministic)
}
func (dst *SkillInfo_C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillInfo_C.Merge(dst, src)
}
func (m *SkillInfo_C) XXX_Size() int {
	return xxx_messageInfo_SkillInfo_C.Size(m)
}
func (m *SkillInfo_C) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillInfo_C.DiscardUnknown(m)
}

var xxx_messageInfo_SkillInfo_C proto.InternalMessageInfo

func (m *SkillInfo_C) GetGuid() int64 {
	if m != nil && m.Guid != nil {
		return *m.Guid
	}
	return 0
}

type SkillInfo_S struct {
	Infos                []*NetSkillInfo `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SkillInfo_S) Reset()         { *m = SkillInfo_S{} }
func (m *SkillInfo_S) String() string { return proto.CompactTextString(m) }
func (*SkillInfo_S) ProtoMessage()    {}
func (*SkillInfo_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_Skill_fb39a603eab4eb9d, []int{1}
}
func (m *SkillInfo_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillInfo_S.Unmarshal(m, b)
}
func (m *SkillInfo_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillInfo_S.Marshal(b, m, deterministic)
}
func (dst *SkillInfo_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillInfo_S.Merge(dst, src)
}
func (m *SkillInfo_S) XXX_Size() int {
	return xxx_messageInfo_SkillInfo_S.Size(m)
}
func (m *SkillInfo_S) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillInfo_S.DiscardUnknown(m)
}

var xxx_messageInfo_SkillInfo_S proto.InternalMessageInfo

func (m *SkillInfo_S) GetInfos() []*NetSkillInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*SkillInfo_C)(nil), "message.SkillInfo_C")
	proto.RegisterType((*SkillInfo_S)(nil), "message.SkillInfo_S")
}

func init() { proto.RegisterFile("Skill.proto", fileDescriptor_Skill_fb39a603eab4eb9d) }

var fileDescriptor_Skill_fb39a603eab4eb9d = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0xce, 0xce, 0xcc,
	0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87, 0x08, 0x2b, 0x29, 0x42, 0x55, 0x79, 0xe6,
	0xa5, 0xe5, 0xc7, 0x3b, 0x0b, 0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x30, 0x07, 0x81, 0xd9, 0x4a, 0x56, 0xc8, 0x4a, 0x82, 0x85, 0xb4, 0xb9, 0x58, 0x33, 0xf3,
	0xd2, 0xf2, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0xa0, 0x06, 0xeb, 0xf9,
	0xa5, 0x96, 0xc0, 0xd5, 0x05, 0x41, 0xd4, 0x38, 0x89, 0x70, 0x71, 0x27, 0xe7, 0xe7, 0xc2, 0x94,
	0x38, 0xb1, 0x82, 0x15, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x67, 0xb0, 0x0e, 0x99, 0x00,
	0x00, 0x00,
}
