// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SystemMsg.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PublicCode_S struct {
	Code                 *Code    `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Cmd                  *int32   `protobuf:"varint,2,opt,name=cmd" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicCode_S) Reset()         { *m = PublicCode_S{} }
func (m *PublicCode_S) String() string { return proto.CompactTextString(m) }
func (*PublicCode_S) ProtoMessage()    {}
func (*PublicCode_S) Descriptor() ([]byte, []int) {
	return fileDescriptor_SystemMsg_504182f90a1af0cf, []int{0}
}
func (m *PublicCode_S) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicCode_S.Unmarshal(m, b)
}
func (m *PublicCode_S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicCode_S.Marshal(b, m, deterministic)
}
func (dst *PublicCode_S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicCode_S.Merge(dst, src)
}
func (m *PublicCode_S) XXX_Size() int {
	return xxx_messageInfo_PublicCode_S.Size(m)
}
func (m *PublicCode_S) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicCode_S.DiscardUnknown(m)
}

var xxx_messageInfo_PublicCode_S proto.InternalMessageInfo

func (m *PublicCode_S) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *PublicCode_S) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func init() {
	proto.RegisterType((*PublicCode_S)(nil), "message.PublicCode_S")
}

func init() { proto.RegisterFile("SystemMsg.proto", fileDescriptor_SystemMsg_504182f90a1af0cf) }

var fileDescriptor_SystemMsg_504182f90a1af0cf = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0xae, 0x2c, 0x2e,
	0x49, 0xcd, 0xf5, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d,
	0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0x71, 0x4a, 0x2c, 0x4e, 0x0d, 0xf3, 0x87, 0x08, 0x2b, 0x39,
	0x73, 0xf1, 0x04, 0x94, 0x26, 0xe5, 0x64, 0x26, 0x3b, 0xe7, 0xa7, 0xa4, 0xc6, 0x07, 0x0b, 0x29,
	0x72, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xf1, 0xea, 0x41,
	0x75, 0xe9, 0x81, 0xa4, 0x83, 0xc0, 0x52, 0x42, 0x02, 0x5c, 0xcc, 0xc9, 0xb9, 0x29, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x20, 0xa6, 0x93, 0x04, 0x17, 0x77, 0x72, 0x7e, 0x2e, 0x4c, 0xad,
	0x13, 0x27, 0xdc, 0x6e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xc2, 0xdd, 0x36, 0x87, 0x00,
	0x00, 0x00,
}
